fix. toolbar disable,view comment not remove
codeigniter4/CodeIgniter4 pull request #3010
Opened 2020-05-18 06:34 UTC by Instrye

- fix #3002. toolbar disable,but view comment not remove.
- delete filter argumets support. because, filter muset `implements FilterInterface`. `before` only receive request. so, if filter argumetns send to `before`, will get an error.
- Alias resolution is no longer done in the `run` method, `Filters::$filtersClass` save alias to class
**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2020-06-02 02:12 UTC, MGatner commented
Thank you @Instrye - this looks like quite a bit of work and some good changes. I don't have my head around it, I'll have to try another day. In the meantime, anybody else willing to give it a review?

2020-07-24 05:48 UTC, paulbalandan commented
This needs to be revised to incorporate changes in `FilterInterface`.

2020-08-12 09:23 UTC, samsonasik commented
@MGatner could you re-check it?

2020-08-12 09:26 UTC, samsonasik commented on system/View/View.php
> +		if (($this->debug && (! isset($options['debug']) || $options['debug'] === true)) && in_array('CodeIgniter\Filters\DebugToolbar', service('filters')->getFiltersClass()['after']))
can use strict in_array check: 

```suggestion
              if (($this->debug && (! isset($options['debug']) || $options['debug'] === true)) && in_array('CodeIgniter\Filters\DebugToolbar', service('filters')->getFiltersClass()['after'], true))
```

2020-08-25 23:40 UTC, MGatner commented on tests/system/Filters/FiltersTest.php
> +				'multipeTest' => [
```suggestion
				'multipleTest' => [
```

2020-08-25 23:41 UTC, MGatner commented on tests/system/Filters/FiltersTest.php
> +					'multipeTest',
```suggestion
					'multipleTest',
```

2020-08-25 23:43 UTC, MGatner commented
A few issues failing the static analysis check, but otherwise this looks good. Waiting on Travis. @samsonasik should we merge despite the CS failures? Or resolve those first?

2020-08-25 23:47 UTC, samsonasik commented
@MGatner I think code static analysis check need to incorporated first: 

```
 ------ ----------------------------------------------------------------------- 
  Line   system/Filters/Filters.php                                             
 ------ ----------------------------------------------------------------------- 
  157    Access to an undefined property                                        
         CodeIgniter\Filters\Filters::$argumentsClass.                          
  183    Access to an undefined property                                        
         CodeIgniter\Filters\Filters::$argumentsClass.                          
  338    Access to an undefined property                                        
         CodeIgniter\Filters\Filters::$argumentsClass.                          
  495    Return typehint of method                                              
         CodeIgniter\Filters\Filters::processAliasesToClass() has invalid type  
         CodeIgniter\Filters\type.                                              
  497    Method CodeIgniter\Filters\Filters::processAliasesToClass() should     
         return CodeIgniter\Filters\type but return statement is missing.      
```

2020-08-25 23:52 UTC, samsonasik commented on system/Filters/Filters.php
> +
new property can be added:

```suggestion

           /** @var array */
          protected $argumentsClass;

```

2020-08-25 23:54 UTC, samsonasik commented on system/Filters/Filters.php
> +	 * @return type
docblock can be updated to:

```suggestion
       * @return void
       * @throws FilterException
```

2020-08-26 18:30 UTC, michalsn requested changes

2020-08-30 17:02 UTC, MGatner commented
@Instrye It looks like one more round of tweaks, if you're available for those.

2020-08-31 09:55 UTC, Instrye commented
😂I want to provide quality phpdoc, But my English level hinders me.

2020-09-01 07:58 UTC, Instrye commented on system/Filters/Filters.php
> +		}
thanks

2020-09-01 19:26 UTC, michalsn approved these changes
Looks good, thanks! 

You only have to resolve some conflicts with the develop branch and I think we're good to go.

2020-09-03 02:14 UTC, Instrye commented
@michalsn Everything's ready.

2020-09-03 05:01 UTC, merged

2020-09-03 05:01 UTC, michalsn commented
Thanks!