Use CLI::getSegment(1) to refer to the first argument
codeigniter4/CodeIgniter4 pull request #3585
Opened 2020-09-02 11:54 UTC by paulbalandan

**Description**
I've noticed that `getSegment`'s code deducts 1 from the index parameter before checking which made me realize that it is one-based instead of zero-based. This PR updates `GeneratorCommand::getClassName()` to use that.

In retrospect, why was it that way?

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2020-09-02 20:37 UTC, paulbalandan commented
I think this should be getSegment(2).

2020-09-03 05:03 UTC, michalsn approved these changes
Just waiting for tests to pass before merging.

2020-09-03 11:54 UTC, MGatner requested changes
Could we get a test case showing what this fixes? How has this been working so far?

2020-09-03 13:09 UTC, paulbalandan commented
> Could we get a test case showing what this fixes? How has this been working so far?

Unfortunately, I think we cannot setup an automated test for this. The concrete classes extending GeneratorCommand all require class names as argument, so the empty string given here will trigger a `CLI::prompt` which is currently untestable. You may test them manually.

Analyzing how CLI parses the arguments and stores them, here is an illustration:
```php
php spark make:controller blog -bare

CLI::getSegment(0) =>> undefined // since we are accessing the -1 index
CLI::getSegment(1) =>> 'make:command' // first segment after the name of invoking program is the name of the command
CLI::getSegment(2) =>> 'blog' // next segments would be the arguments passed to the command
CLI::getOption('bare') =>> true // since it is set as a flag
```

2020-09-03 13:10 UTC, paulbalandan commented
> Could we get a test case showing what this fixes? How has this been working so far?

Unfortunately, I think we cannot setup an automated test for this. The concrete classes extending GeneratorCommand all require class names as argument, so the empty string given here will trigger a `CLI::prompt` which is currently untestable. You may test them manually.

Analyzing how CLI parses the arguments and stores them, here is an illustration:
```php
php spark make:controller blog -bare

CLI::getSegment(0) =>> undefined // since we are accessing the -1 index
CLI::getSegment(1) =>> 'make:command' // first segment after the name of invoking program is the name of the command
CLI::getSegment(2) =>> 'blog' // next segments would be the arguments passed to the command
CLI::getOption('bare') =>> true // since it is set as a flag
```

2020-09-03 13:28 UTC, merged

2020-09-11 04:47 UTC, John-Betong commented
I have just been working on my dynamic menu system and had to count($uri->getSegments()) to prevent the following error being thrown:
#### // $tmpSub = $uri->getSegment(2) // MAYBE THROW ERROR  
Request URI segment is out of range:

2020-09-11 05:22 UTC, michalsn commented
@John-Betong You can use `setSilent()` instead: https://codeigniter4.github.io/userguide/libraries/uri.html#uri-segments

2020-09-11 06:03 UTC, John-Betong commented
@michalsn,
> @John-Betong You can use `setSilent()` instead: https://codeigniter4.github.io/userguide/libraries/uri.html#uri-segments

That's new to me and could come in handy some time in the future.

I don' think I like hiding exceptions, far prefer to know what is happening.

I prefer testing for results and using if/else/endif statements.