[FEAT] New encryption handler: SodiumHandler
codeigniter4/CodeIgniter4 pull request #3667
Opened 2020-09-21 12:34 UTC by paulbalandan

**Description**
This PR adds the SodiumHandler as additional encryption handler.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

2020-09-21 14:51 UTC, paulbalandan commented
How do I enable the sodium extension in Travis?

2020-09-21 18:17 UTC, michalsn commented
You can try to use `dist: bionic` or `focal` instead of `xenial`.

2020-09-23 10:44 UTC, MGatner reviewed
Wow this looks like a lot of work. 😳 The code looks good at first scroll through. I haven't really used the encryption library and don't know anything about Sodium so I will leave this for others' reviews.

2020-09-24 17:02 UTC, michalsn requested changes
It looks quite solid to me. I have few small requests and one question... or two :)

2020-09-24 17:07 UTC, michalsn commented on user_guide_src/source/libraries/encryption.rst
> +	$key = Encryption::createKey(24);
Can we remove it for now? I don't want to encourage users to play with this variable if they don't know what they're doing.

2020-09-25 08:28 UTC, paulbalandan commented on system/Encryption/Handlers/SodiumHandler.php
> +		$paddedLength  = $this->blockSize <= 512 ? $this->blockSize : 512;
I do not claim to be a cryptography expert, but my readings on `libsodium` I found no cases for block sizes exceeding 512.

https://libsodium.gitbook.io/doc/secret-key_cryptography/aead#availability-and-interoperability

The RFC on which the libsodium is based for PHP follows the IETF version of ChaCha20-Poly1305 which defines 512 bits for block size. The original version and the extended version (XChaCha20-Poly1305) also uses 512 bits. 

Also, I've read that block sizes should be nonzero and not too long in order to prevent buffer overflow. In the documentation I assume the figures given for the block sizes are the upper limits.

2020-09-25 08:44 UTC, paulbalandan commented on system/Encryption/Handlers/SodiumHandler.php
> +		$paddedLength  = $this->blockSize <= 512 ? $this->blockSize : 512;
I tried to introspect the libsodium code in `C` to determine the value of `SIZE_MAX` to determine the max allowed for block size...but I'm still trying. 😂

2020-09-25 16:25 UTC, michalsn commented on system/Encryption/Handlers/SodiumHandler.php
> +		$paddedLength  = $this->blockSize <= 512 ? $this->blockSize : 512;
The block size you're referring to is used inside the cryptographic algorithm.

I haven't checked it earlier but now I found this: https://libsodium.gitbook.io/doc/padding
And from what I see it's just `length & <block size mask>`, so I don't think we should add any limit to it. It's just padding added to the original message before encryption so If someone needs a 1024 block, so be it.

Also, the default 512 block size seems a little too big in my opinion. It will produce huge encryption strings even for simple messages. I was thinking about something much lower for default, like 16 or 32?

2020-09-25 16:28 UTC, michalsn requested changes
We still need a description of what this value (block size) is for in the user guide (comment in the code is probably not enough - most people won't be looking into the code anyway).

An example from libsodium-php:
> Sometimes, the length of a message may provide a lot of information about its nature. If a message is one of "yes", "no" and "maybe", encrypting the message doesn't help: knowing the length is enough to know what the message is.
Padding is a technique to mitigate this, by making the length a multiple of a given block size.

2020-09-26 11:58 UTC, paulbalandan commented on system/Encryption/Handlers/SodiumHandler.php
> +		$paddedLength  = $this->blockSize <= 512 ? $this->blockSize : 512;
Ooh. I was mistaken. Thanks for the clarification.

I've read some more and looks like the libsodium author is suggesting a minimum of 16.

2020-09-26 12:08 UTC, michalsn commented on system/Encryption/Handlers/SodiumHandler.php
> +		$paddedLength  = $this->blockSize <= 512 ? $this->blockSize : 512;
OK, that will be great - thank you :)

2020-09-27 17:49 UTC, michalsn approved these changes
Thank you for working on this!

2020-09-27 17:50 UTC, merged