New Array Helper Function
codeigniter4/CodeIgniter4 pull request #3684
Opened 2020-09-26 00:18 UTC by savasdersimcelik

Returns the value of an element with a key value in an array of uncertain depth.

Each pull request should address a single issue and have a meaningful title.

**Description**
Explain what you have changed, and why.

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

---------Remove from here down in your description----------

**Notes**
- Pull requests must be in English
- If the PR solves an issue, reference it with a suitable verb and the issue number
(e.g. fixes <hash>12345)
- Unsolicited pull requests will be considered, but there is no guarantee of acceptance
- Pull requests should be from a feature branch in the contributor's fork of the repository
  to the develop branch of the project repository

2020-09-26 05:55 UTC, samsonasik commented
please follow ci coding standard, you can fix with run the following command:

```bash
composer update && vendor/bin/phpcbf --standard=./vendor/codeigniter4/codeigniter4-standard/CodeIgniter4 system/Helpers/array_helper.php
```

2020-09-26 10:29 UTC, MGatner commented
Please do run the style fixer as @samsonasik mentioned. We will also need some tests - should be fairly easy just to add them to the ArrayHelper tests.

2020-09-26 15:05 UTC, savasdersimcelik commented
> please follow ci coding standard, you can fix with run the following command:
> 
> ```shell
> composer update && vendor/bin/phpcbf --standard=./vendor/codeigniter4/codeigniter4-standard/CodeIgniter4 system/Helpers/array_helper.php
> ```

Thank you. I ran the command you said.

2020-09-26 15:21 UTC, samsonasik commented on system/Helpers/array_helper.php
> +			else
else can be removed as already return early

2020-09-26 15:21 UTC, paulbalandan commented on system/Helpers/array_helper.php
> +		if (is_array($array))
No need for the `is_array` check since it is already typehinted in the parameter.

2020-09-26 15:21 UTC, paulbalandan commented on system/Helpers/array_helper.php
> +			{
No need for `else` since the preceding statement is a `return`.

2020-09-26 18:12 UTC, michalsn requested changes

2020-09-28 19:48 UTC, MGatner commented
Looking good! Still need some tests though. Check out **tests/system/Helpers/ArrayHelperTest.php** - it should be fairly easy to paste some of the existing tests and modify them for some simple cases for your new function.

2020-09-28 21:05 UTC, savasdersimcelik commented
> Looking good! Still need some tests though. Check out **tests/system/Helpers/ArrayHelperTest.php** - it should be fairly easy to paste some of the existing tests and modify them for some simple cases for your new function.


Hello, of course, I added the test functions.

2020-09-30 13:25 UTC, MGatner commented
Thanks for the tests! I might refactor them to use a provider to make it a little cleaner, but I think this is functionally very sound.

2020-09-30 13:27 UTC, savasdersimcelik commented
> Thanks for the tests! I might refactor them to use a provider to make it a little cleaner, but I think this is functionally very sound.

Of course, how you see fit.

2020-09-30 13:34 UTC, closed without merging

2020-09-30 13:44 UTC, MGatner commented
@savasdersimcelik I'm sorry, I messed up the upstream push and it locked my access to your branch. I will open a new PR with your changes but you should probably rebase your `develop` before you work on it any more.