DX: Normalise whitespaces
codeigniter4/CodeIgniter4 pull request #3860
Opened 2020-11-06 13:23 UTC by paulbalandan

**Description**
Normalizes whitespaces by removing unnecessary ones and adding where it would be needed.

**Checklist:**
- [x] Securely signed commits

2020-11-06 21:08 UTC, MGatner requested changes
Mostly good changes here. I made a few specific notes, and a list of the files I think were better before. Generally I don't like adding newlines between a bunch of single-line properties - I think that covers a lot of these, so if there is a rule we could tweak around that it might save some time.

I don't like the changes to:
* Constants
* ContentSecurityPolicy
* Logger
* ResponseInterface
* MockAppConfig
* MockCLIConfig
* bootstrap.php
* all the tests/_support/Commands headers
* tests/EventModel
* tests/CommandRunnerTest
* all the tests/Cache/* headers
* tests/SImpleConfig
* tests/ModelTest "new class extends Entity"
* tests/HoneypotTest
* tests/CookieHelperTest

I need to look at Email and the large diffs at the end separately.

2020-11-06 21:08 UTC, MGatner commented on system/View/Cell.php
> +			&& ((! array_key_exists($refParams[0]->name, $paramArray)) || (array_key_exists($refParams[0]->name, $paramArray) && count($paramArray) !== 1)))
This should either be three lines or one line.

2020-11-06 21:08 UTC, MGatner commented on tests/_support/Language/en/Core.php
> - * @codeCoverageIgnore
Was this intentionally removed?

2020-11-08 12:01 UTC, paulbalandan commented
> Mostly good changes here. I made a few specific notes, and a list of the files I think were better before. Generally I don't like adding newlines between a bunch of single-line properties - I think that covers a lot of these, so if there is a rule we could tweak around that it might save some time.
> 
> I don't like the changes to:
> 
> * Constants
Added rule '||' to 'align_single_space_minimal'

> * ContentSecurityPolicy
My intention for enabling class_attributes_separation is to properly put docblocks there afterwards

> * Logger
Reverted

> * ResponseInterface
Reverted

> * MockAppConfig
Reverted

> * MockCLIConfig
Reverted

> * bootstrap.php
Added rule '||' to 'align_single_space_minimal'

> * all the tests/_support/Commands headers
This is consistent with PSR12

> * tests/EventModel
Reverted

> * tests/CommandRunnerTest
Reverted

> * all the tests/Cache/* headers
The headers are consistent with PSR12

> * tests/SImpleConfig
Reverted

> * tests/ModelTest "new class extends Entity"
class_attribute_separation is now disabled

> * tests/HoneypotTest
Reverted

> * tests/CookieHelperTest
Reverted

> I need to look at Email and the large diffs at the end separately.

2020-11-08 12:02 UTC, paulbalandan commented on app/Views/errors/html/error_exception.php
> +					<li><?= htmlspecialchars(clean_path($file), ENT_SUBSTITUTE, 'UTF-8') ?></li>
Ah yes. To be removed.

2020-11-08 12:03 UTC, paulbalandan commented on app/Views/errors/html/error_exception.php
> +				CodeIgniter: <?= \CodeIgniter\CodeIgniter::CI_VERSION; ?>
Same. Three rules applied here.

2020-11-08 12:09 UTC, paulbalandan commented on tests/_support/Language/en/Core.php
> - * @codeCoverageIgnore
Ah yes. This was a stray header.

2020-11-09 16:28 UTC, MGatner requested changes
This one is pretty painful to review, it might help to break it up by subfolders or something.

Still some of the split properties I don't like, e.g.:
* tests/_support/Commands/ParamsReveal.php
* tests/system/Commands/GenerateKeyTest.php
* tests/system/Config/fixtures/Encryption.php 
* tests/system/Database/Migrations/MigrationRunnerTest.php

That last one (Migration Runner Test) has some weird spaces in the object array cast too.

2020-11-15 13:06 UTC, paulbalandan commented
> This one is pretty painful to review, it might help to break it up by subfolders or something.

Will do.

2020-11-15 13:06 UTC, closed without merging