Model: support returning array indexed by a specified column
codeigniter4/CodeIgniter4 pull request #3895
Opened 2020-11-16 21:14 UTC by rmilecki

```
This allows Model users to get array or results indexed with a specific
column, $primaryKey by default. It can be simply used as:

$model->indexed()->findAll()

It may be useful e.g. for generating array to be used with
form_dropdown().

Signed-off-by: Rafał Miłecki <rafal@milecki.pl>
```

**Description**
I personally use it for `form_dropdown()` and found someone else requesting for it as well in forum thread [ Query result as an indexed array or object by index of choice ](https://forum.codeigniter.com/thread-76215.html). I was told to submit a Pull Request, so I share my code.

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

2020-11-17 01:05 UTC, OJMichael commented on system/Model.php
> +		$this->tempReturnIndexed = $key === null ? $this->primaryKey : $key;
This could also be written as:

```php
$this->tempReturnIndexed = $key ?? $this->primaryKey;
```

2020-11-17 06:43 UTC, paulbalandan requested changes
Please update your fork first then rebase the changes to your `model-indexed` branch. You can use these steps, assuming `origin` is your fork's remote and `upstream` is the remote of codeigniter4 repo.

```
git checkout develop
git pull upstream develop
git push
git checkout model-indexed
git rebase develop
git push --force
```

2020-11-17 09:44 UTC, craigrodway commented
The Yii framework has this functionality in their Array helper, which I think is a better place to put it rather than only in the model - allowing for more re-use.

https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseArrayHelper.php#L367-L500

2020-11-17 10:40 UTC, sfadschm commented
> The Yii framework has this functionality in their Array helper, which I think is a better place to put it rather than only in the model - allowing for more re-use.
> 
> https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseArrayHelper.php#L367-L500

I also implemented such functionality in my CI4 array helper (although not as advanced).
Maybe a combination would be nice, so that we have the Array helper available for all occasions, but still have the proposed `indexed` method in the model for convenience? (Which would then of course use the helper method.)

2020-11-19 20:54 UTC, sfadschm commented
Just some more notes on this, as I am thinking about something similar atm:
1. The database column which is used to reindex the array might not have the `unique` attribute, so handling of duplicate values should be considered. (This could, e.g., be canceling the reindexing totally, keeping only the first/last occurence of a key value or even grouping array elements with the same key value into subarrays.)
2. Model queries might return arrays of entities. In this case, a simple `array_column` will likely not work.
3. Just an idea right now, but maybe the `array_helper` functions, such as `dot_array_search` could be used to add more flexibility, but might also increase load.

2021-03-17 05:05 UTC, paulbalandan commented
@rmilecki are you able to do the changes and fork update?? If we'll not hear from you soon, we'll close this as abandoned.

2021-03-18 05:32 UTC, closed without merging