simple error_log Log Handler
codeigniter4/CodeIgniter4 pull request #3898
Opened 2020-11-17 14:22 UTC by rwillert

**Description**
A simple Log Handler for error_log.
We use this Handler to log to stdout for Docker Container.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

2020-11-17 15:41 UTC, paulbalandan requested changes

2020-11-17 15:41 UTC, paulbalandan commented on system/Log/Handlers/ErrorlogHandler.php
> +
```suggestion
```

No need to call parent constructor if no special initializations will be made by extending class.

2020-11-17 15:41 UTC, paulbalandan commented on system/Log/Handlers/ErrorlogHandler.php
> +	//--------------------------------------------------------------------
```suggestion
```
Remove

2020-11-17 15:41 UTC, paulbalandan commented on tests/system/Log/Handlers/ErrorlogHandlerTest.php
> +
```suggestion
```
No need.

2020-11-17 15:41 UTC, paulbalandan commented on tests/system/Log/Handlers/ErrorlogHandlerTest.php
> +class ErrorlogHandlerTest extends \CodeIgniter\Test\CIUnitTestCase
```suggestion
use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\Mock\MockLogger as LoggerConfig;

final class ErrorlogHandlerTest extends CIUnitTestCase
```

2020-11-17 15:41 UTC, paulbalandan commented on tests/system/Log/Handlers/ErrorlogHandlerTest.php
> +namespace CodeIgniter\Log\Handlers;
```suggestion
<?php

namespace CodeIgniter\Log\Handlers;
```

2020-11-17 15:41 UTC, paulbalandan commented on tests/system/Log/Handlers/ErrorlogHandlerTest.php
> +
```suggestion
```
Remove unnecessary whitespace

2021-02-12 04:23 UTC, lonnieezell commented
@rwillert Are you able to make these revisions?

2021-02-24 16:21 UTC, paulbalandan approved these changes
Actually I have sent a replacement PR due to the inactivity, but since you've worked on this I'll just modify my PR as an enhancement. 😁

2021-02-24 16:22 UTC, merged

2021-02-24 18:55 UTC, MGatner commented
Whoops, I didn't notice that! Glad you were still able to use the content.