Throttle: allow removal of throttler buckets
codeigniter4/CodeIgniter4 pull request #3907
Opened 2020-11-19 10:50 UTC by element-code

This allows to manual remove throttler buckets manually.
E.g. after paying a plan or a successful login.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2020-11-20 12:20 UTC, paulbalandan requested changes
This needs some tests and user guide mention.

2020-11-20 12:20 UTC, paulbalandan commented on system/Throttle/Throttler.php
> +	public function remove(string $key) : void
```suggestion
	public function remove(string $key): void
```

2020-12-08 03:55 UTC, lonnieezell commented
@element-code are you able to add tests to this?

2020-12-08 09:10 UTC, element-code commented
Yes, but it will take some time, see https://github.com/codeigniter4/CodeIgniter4/pull/3911#issuecomment-740486515
Help is appreciated :)

2021-02-24 02:26 UTC, paulbalandan approved these changes

2021-02-24 02:27 UTC, merged