Feature: Validation: allow anonymous functions as rules
codeigniter4/CodeIgniter4 pull request #3913
Opened 2020-11-19 12:56 UTC by element-code

Allows to use an anonymous function with a name as a rule:
```php
$rules = [
  'max_length[191]',
  [
    'foobar',
    function(mixed $value, array $data) {
      return (bool) $value;
    },
  ],
];
```
Anonymous-function rules also require to be wrapped in an array and have a name for errors as first array item

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2020-11-19 12:56 UTC, element-code commented
This needs a user guide update, feel free to commit

2020-11-20 12:24 UTC, paulbalandan requested changes
Aside from the user guide update, this would need some testing.

2020-12-08 03:59 UTC, lonnieezell commented
I have no problems with this addition, but will need tests and user guide updates or we'll have to close. @element-code are you able to add those?

2020-12-08 09:05 UTC, element-code commented
Yes, but it will take some time, see https://github.com/codeigniter4/CodeIgniter4/pull/3911#issuecomment-740486515
Help is appreciated.

2021-02-24 01:43 UTC, MGatner commented
I think this is maybe related to your other Validation PR? I will wait to hear back on the one first.

2021-02-24 09:23 UTC, element-code commented
@MGatner no, this is completely detatched (and doesnt support placeholders anyway rn) :)

2022-01-05 04:05 UTC, lonnieezell commented
This has gone over a year without the tests being added. Closing.

2022-01-05 04:05 UTC, closed without merging