Build Cookie Class
codeigniter4/CodeIgniter4 pull request #3983
Opened 2020-12-12 23:34 UTC by mostafakhudair

Separated cookie class will help us to use cookie in whole  framework such as. Security::sendCookies(), Session::setCookies(), Response::sendCookies(), now we area able to do this from one main class \CodeIgniter\Cookie\Cookie

after merge: i'll update other classes with new cookie class methods
and will deprecate some methods and properties

userguide not finished yet

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

2020-12-13 04:45 UTC, mostafakhudair commented
Fails i'll fix when i back to home

2020-12-13 13:15 UTC, MGatner commented
Initially looks good. I don't have time to do a proper review but I approve the approach. Thank you!

2020-12-14 01:33 UTC, mostafakhudair commented
Some of tests were failed I'll fix it soon

2020-12-14 08:34 UTC, paulbalandan commented
Before you progress further, please rename your subsequent commits to be more descriptive of the change. If it will just be the same, I assume that it is only an amended commit and should be forced pushed instead.

2020-12-15 17:57 UTC, paulbalandan requested changes
The initial implementation is good for me. I have some comments though. My major concern, however, is I don't like the `Cookie` class performing two functions here: representing a single cookie, through extending `BaseCookie`, and representing at the same time a collection of cookies, through implementing `CookieInterface`. These two functions should be on two distinct classes. Please read through my comments for my explanations.

2020-12-15 17:57 UTC, paulbalandan commented on system/Cookie/BaseCookie.php
> +		foreach (get_class_vars(get_class($this)) as $key => $value)
Is there a reason on using `get_class_vars(get_class($this))` instead of using `get_object_vars($this)`?

2020-12-15 17:57 UTC, paulbalandan commented on system/Cookie/BaseCookie.php
> +        $this->samesite = ucfirst($samesite);
Kindly align this one.

2020-12-15 17:57 UTC, paulbalandan commented on system/Cookie/BaseCookie.php
> +		foreach (get_class_vars(get_class($this)) as $key => $value)
Same comment with `get_class_vars` above.

2020-12-15 17:57 UTC, paulbalandan commented on system/Cookie/BaseCookie.php
> +			if (property_exists($this, $key) && isset($this->properties[$key]))
```suggestion
			if (isset($this->properties[$key]))
```
I don't think `property_exists` is needed as you are checking already on the child cookie's properties.

2020-12-15 17:57 UTC, paulbalandan commented on system/Cookie/BaseCookie.php
> +			if (property_exists($this, $key) && isset($this->properties[$key]))
```suggestion
			if (isset($this->properties[$key]))
```

2020-12-15 17:57 UTC, paulbalandan commented on system/Cookie/Cookie.php
> +
This constructor can be removed if no special initializations would be done by the implementing child cookie.

2020-12-15 17:57 UTC, paulbalandan commented on system/Cookie/Cookie.php
> +	protected $cookies = [];
I thought the `Cookie` class will be representing a single web cookie, so I'm surprised to see this was actually a "jar of cookies" class. I would expect, and others might too, that this is a single cookie object representation. My suggestion is to split the unique Cookie class from the Cookie collection capacity.

In Laravel, they have this `CookieJar` class which is the "jar" for all cookies, and calling a cookie would be done through this class. In CakePHP I think it is named `CookieCollection`.

So basically, this class would be split:
- `Cookie` representing a single web cookie which properties like `name` and `prefix` would be accessed.
- `CookieCollection` or `CookieJar` (or whatever you like) creating and storing all `Cookie` objects like some sort of a factory class.

2021-01-05 01:11 UTC, MGatner commented
This looks like a real quality PR. @paulbalandan it looks to me like your requests have been addressed - okay with merging? I don't do a lot with cookies so would like someone else to confirm the merge.

2021-01-05 01:12 UTC, MGatner approved these changes

2021-01-05 06:35 UTC, paulbalandan commented
Oh, missed this one. I'll do another review this evening after work. 😄

2021-01-05 15:50 UTC, paulbalandan reviewed
I see that you now have a separate `CookiePresenter` class. Thanks for indulging my reviews. Allow me to make some more.

In your proposed implementation, `CookiePresenter` is the single web cookie while `Cookie` is the cookie collection. I believe it would be more natural, or more fluent, to have the opposite. `Cookie` as the single web cookie class, while `CookiePresenter` as the collection of cookies.

Two interfaces:
- `CookieInterface` -  interface for single web cookie tokens. This would contain the methods defined in the proposed `BaseCookie` class.
- `CookiePresenterInterface` - interface for cookie collection objects. This would contain the methods in your proposed `CookieInterface`.

Abstraction
- `BaseCookie` would be implementing `CookieInterface`, providing concrete classes to do little changes
- `Cookie` would be extending `BaseCookie`. In the proposed implementation, BaseCookie accepts a `CookieConfig` instance while `CookiePresenter` expects several arguments. Maybe we can do is the `Cookie` will inherit the `CookieConfig` instance then just override the values using the `set()` method.

Services
- `Services::cookie()` will now return a `CookiePresenter` if no args supplied, but an instance of `Cookie` if some args are supplied, or `null` if inexistent
- Getting cookies from services will return either null or instance of `Cookie`

2021-01-05 15:50 UTC, paulbalandan commented on system/Cookie/BaseCookie.php
> +		$this->samesite = ucfirst(strtolower($samesite));
I think we should be consistent in throwing exceptions here if wrong samesite is given. That way, developers won't get confused why there are setting this value but another one gets assigned. It's like telling them directly the problem they're doing.

2021-01-05 15:50 UTC, paulbalandan commented on system/Cookie/Exceptions/CookieException.php
> +class CookieException extends FrameworkException implements ExceptionInterface
No need to reimplement the interface. `FrameworkException` already implements it.

2021-01-09 06:37 UTC, mostafakhudair commented
Thanks for the review with many good points, but about current names  I think`Cookie` for cookie collection and `CookiePresenter`for present single web cookie is much cooler regardless of the logic,, I belive that you are right but i would like to hear others opinions

2021-01-09 19:19 UTC, sfadschm commented
Personally, I would go for `Cookie` to present a single cookie. 
How is this handled with other collections throughout the framework?
E.g., for files, we have `FileCollection` and `File`.

2021-01-11 17:05 UTC, mostafakhudair commented
@MGatner what about this PR :)

2021-01-21 04:01 UTC, mostafakhudair commented
@michalsn would you take a look here please?

2021-02-12 16:46 UTC, closed without merging