feat: make migration/seed settings flexible on database testing
codeigniter4/CodeIgniter4 pull request #3993
Opened 2020-12-16 03:14 UTC by kenjis

**Description**
Now you can't disable migration on database testing if you want.
And running migration/seed on each test may slow tests.

- You can disable migration: `$migrate = false`
- You can run migration only once: `$migrateOnce = true`
- You can run seed only once: `$seedOnce = true`

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2020-12-16 12:31 UTC, MGatner reviewed
I will have to look at this one on mobile, but I like breaking these out. First and foremost we must be absolutely sure that current tests will still work after this change (I.e. still respects `$refresh`). Second IMO we should go ahead and deprecate `$refresh` and rely on these going forward. 

These changes will also require updates to the User Guide.

2020-12-18 11:15 UTC, kenjis commented
Updated the User Guide.

2020-12-19 01:01 UTC, kenjis commented
Only PHP 7.3 - Postgre failed. Why?
https://github.com/codeigniter4/CodeIgniter4/pull/3993/checks?check_run_id=1576289817

2020-12-19 01:03 UTC, MGatner commented
@kenjis it's been happening from time to time. Not related to your PR, we need to look into why the test table is persisting.

2020-12-19 01:21 UTC, kenjis commented
I see. Thanks!

2020-12-21 10:43 UTC, kenjis commented
`PHP 7.3 - Postgre` failed again.
https://github.com/codeigniter4/CodeIgniter4/pull/3993/checks?check_run_id=1587713000

2020-12-21 13:12 UTC, paulbalandan commented
> `PHP 7.3 - Postgre` failed again.
> https://github.com/codeigniter4/CodeIgniter4/pull/3993/checks?check_run_id=1587713000

You just need to re-run actions until it goes green.

2020-12-21 23:48 UTC, kenjis commented
@Panda666Plus How do I re-run?

2020-12-22 00:00 UTC, kenjis commented
I rebased. Can #4015 help?

2020-12-22 00:27 UTC, kenjis commented
Oh no! `PHP 7.3 - Postgre` and `PHP 7.4 - Postgre` failed...

2020-12-22 00:31 UTC, kenjis commented
```
There was 1 failure:

1) CodeIgniter\Database\Live\ForgeTest::testAddFields
Array
(
    [0] => stdClass Object
        (
            [name] => id
            [type] => integer
            [default] => nextval('db_forge_test_fields_id_seq'::regclass)
            [max_length] => 32
        )

    [1] => stdClass Object
        (
            [name] => active
            [type] => integer
            [default] => 0
            [max_length] => 32
        )

    [2] => stdClass Object
        (
            [name] => username
            [type] => character varying
            [default] => 
            [max_length] => 255
        )

    [3] => stdClass Object
        (
            [name] => name
            [type] => character varying
            [default] => 
            [max_length] => 255
        )

)

Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'integer'
+'character varying'

/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/Live/ForgeTest.php:605

--
```

2020-12-22 23:56 UTC, kenjis commented
All tests passed.

2020-12-29 05:24 UTC, kenjis commented
@MGatner Is something wrong with this PR?

2020-12-29 12:40 UTC, MGatner commented
Not necessarily! It's more complicated than I am able to review on mobile, which is where I do most of my reviews. I will set aside some desktop time later to do it.

2020-12-29 12:46 UTC, kenjis commented
@MGatner Okay, thanks!

2020-12-29 19:29 UTC, MGatner requested changes
Generally this looks good. My main concern is around the "once" aspect. As is, with the `private` scope on the flags, migrations & seeds will only run once *for the entire run of PHPUnit*, and yet will be dependent on the class-specific settings of whichever test case is run first. Consider these three test cases all in the same project:
```

class FooTest extends CIDatabaseTestCase
{
	protected $migrateOnce = true;
	protected $namespace   = 'Tests\Support';
}

class BarTest extends CIDatabaseTestCase
{
	protected $migrateOnce = false;
	protected $namespace   = null;
}

class BamTest extends CIDatabaseTestCase
{
	protected $migrateOnce = true;
	protected $namespace   = 'App';
}
```
Depending on which are run and in which order (and by which thread) they could all leave the database in very different states.

In my opinion, the "once" methods should apply per test case (file), rather than for the whole suite - and if we want to offer the option for a single static database test configuration then it should be handled in a bootstrap, not the test cases themselves.

I hope that makes sense.

2020-12-30 01:03 UTC, kenjis commented
@MGatner Thank you for the review.

See https://github.com/codeigniter4/CodeIgniter4/pull/3993/files#diff-7591a921e2ba957a20a6e334d50bb134de0a53a4c4c4a3f01e27d001b9bae4c6R449-R458
It resets the private properties after each test class.
So I think the "once" methods apply per test case (file).

I added test for `$migrateOnce`.

2020-12-30 12:53 UTC, MGatner commented
Oh! Sorry then, that was my mistake. I wonder what kind of weird scopiness is happening that `private static` is applied for every file? Maybe each child class inherits the original static property with `false` and then sets it to `true` at the local scope? @samsonasik help?

Given this, I approve the PR, but I will wait for merge.

2020-12-30 13:00 UTC, samsonasik approved these changes

2020-12-30 13:00 UTC, samsonasik commented
I am ok with this 👍

2020-12-30 13:04 UTC, MGatner commented
@samsonasik do you understand how the scoping is working out such that the "once" variables are toggled for every file?

2020-12-30 13:19 UTC, samsonasik commented
@MGatner that rely on `doneSeed` ?

2020-12-30 13:29 UTC, MGatner commented
Yes. Since `$doneSeed` is `private static` I would expect it to be set once for the entire test suite and thus seeding would only happen one time. But @kenjis confirms that it actually resets between files, which makes me think it must be something with the scoping I don't understand.

2020-12-30 18:12 UTC, paulbalandan commented
This method is called after the test suite class is tested:

```php
	/**
	 * Reset $doneMigration and $doneSeed
	 *
	 * @afterClass
	 */
	public static function resetMigrationSeedCount()
	{
		self::$doneMigration = false;
		self::$doneSeed      = false;
	}
```

Notice the `@afterClass` annotation in the doc block. PHPUnit calls this static method after all test methods have been run in the test class. It is like implicitly calling `tearDownAfterClass` method. See [`@afterClass`](https://phpunit.readthedocs.io/en/9.5/annotations.html?highlight=afterClass)

2020-12-30 18:12 UTC, paulbalandan approved these changes

2021-01-05 01:13 UTC, MGatner commented
I totally missed that. Thanks for explaining 🤩

2021-01-05 01:13 UTC, merged