$links as private variable
codeigniter4/CodeIgniter4 pull request #4018
Opened 2020-12-22 10:37 UTC by totoprayogo1916

**Description**
Convert `$links` as private variable

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

2020-12-22 10:47 UTC, samsonasik commented on system/Pager/PagerRenderer.php
> -
if it going to happen, it needs return early like this:

if $this->links !== [] 
{
    return $this->links; 
}

2020-12-22 13:21 UTC, samsonasik commented
could you provide the use case for make it property?

2020-12-22 15:22 UTC, MGatner requested changes

2020-12-22 15:22 UTC, MGatner commented on system/Pager/PagerRenderer.php
> +	 * Links to dipsplay
Typo
```suggestion
	 * Links to display
```

2020-12-22 15:22 UTC, MGatner commented on system/Pager/PagerRenderer.php
> +	private $links = [];
`$last` technically can be `< 1` so one empty array is a valid return for `links()` already. This should start as `null` and be checked as such for processing.
```suggestion
	 * @var array|null
	 */
	private $links;
```

2020-12-22 15:22 UTC, MGatner commented on system/Pager/PagerRenderer.php
```suggestion
		if (isset($this->links))
		{
			return $this->links;
		}

		$this->links = [];
```

2020-12-24 09:00 UTC, closed without merging

2020-12-24 12:38 UTC, MGatner commented
@totoprayogo1916 did you abandon this?

2020-12-24 12:43 UTC, totoprayogo1916 commented
> @totoprayogo1916 did you abandon this?

I think yes @MGatner . It might even be complicated.