feat: add property accessor to PagerRenderer
codeigniter4/CodeIgniter4 pull request #4141
Opened 2021-01-21 02:51 UTC by kenjis

**Description**
Add property accessor to PagerRenderer.
To generate Pager HTML that is the same as CI3's.
The template would be like this:
```php
    <?php if ($pager->hasPreviousPage()) : ?>
    <a href="<?= $pager->getFirst() ?>" data-ci-pagination-page="<?= $pager->first ?>" rel="start">&laquo;First</a>
    <a href="<?= $pager->getPreviousPage() ?>" data-ci-pagination-page="<?= $pager->current - 1 ?>" rel="prev">&lt;</a>
    <?php endif ?>
```

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2021-01-23 11:16 UTC, paulbalandan reviewed
Please rebase.

2021-01-23 11:16 UTC, paulbalandan commented on system/Pager/PagerRenderer.php
> +		throw new InvalidArgumentException('No such a property: ' . $key);
```suggestion
		throw new InvalidArgumentException('No such property: ' . $key);
```

2021-01-23 12:58 UTC, MGatner requested changes

2021-01-23 12:58 UTC, MGatner commented on tests/system/Pager/PagerRendererTest.php
> +		$this->expectExceptionMessage('No such a property: properyNeverEverExists');
```suggestion
		$this->expectExceptionMessage('No such property: properyNeverEverExists');
```
Need to update the test case too!

2021-01-23 13:39 UTC, iRedds commented
Maybe change all properties to public?

2021-01-23 13:49 UTC, kenjis commented
@iRedds I don't need public properties. I just need to get (read) them, not need to write them.

2021-01-23 14:33 UTC, iRedds commented
@kenjis Who cares. Properties are defined in the constructor.

2021-01-23 14:37 UTC, kenjis commented on tests/system/Pager/PagerRendererTest.php
> +		$this->expectExceptionMessage('No such a property: properyNeverEverExists');
@MGatner Thank you. I fixed.

2021-01-23 14:39 UTC, kenjis commented
@iRedds I don't need public properties. Do you need public properties?

2021-01-23 14:47 UTC, paulbalandan approved these changes

2021-01-23 15:07 UTC, iRedds commented
If you don't need public properties, don't change their values.
I don't see any point in this pager as part of the framework. I understand that you are doing them read-on.

But why not just make them public? They only work with a template anyway.

2021-01-23 15:40 UTC, MGatner commented
Public properties should be avoided unless the class is intentionally a mutable one (like Entity). I would like less public properties in the framework overall, not more. An accessory is the correct way to handle this.

2021-01-23 17:56 UTC, michalsn commented
Since we are working with these properties inside the class, we shouldn't allow them to be set from outside the class as this can lead to problems.

2021-01-23 17:56 UTC, michalsn approved these changes

2021-01-23 18:52 UTC, iRedds commented
It may be better to use getters in this case than the magic method?

2021-01-23 21:32 UTC, MGatner commented
Getters would be the standard way but I believe the point of the PR was to allow backwards-compatibility with the "CI3 way". I don't have a particular issue with the magic method as long as it doesn't mess up the static analysis.

2021-01-23 22:56 UTC, kenjis commented
@iRedds 
I just implemented getters with the magic method.
Do you mean having 6 getter methods like `getCurrent()` is better than having `__get()`?

2021-01-24 01:10 UTC, iRedds commented
@kenjis In this case, any property added to the class in the future, but not intended for public use, will be automatically accessed using the magic method.
I think this is not entirely correct.

2021-01-24 06:20 UTC, kenjis commented
@iRedds 
When a property will be added to the class in the future, but not intended for public use, 
we can restrict accessing the property.

2021-01-24 13:20 UTC, MGatner commented
In general I think using getter methods is better. @kenjis I would like to hear how much of the goal of this PR is supporting the CodeIgniter 3 direct access method versus just getting at the data.

2021-01-25 19:55 UTC, michalsn commented
The only downside is that "natural" getters for these properties are in most cases already taken, so we would have to come up with something more "complicated". And this is probably the only reason in favor of using the magic method for me.

Having something like `$pager->getPropertyPrevious()` would be more elegant than writing `$pager->current - 1`. However, I'm not sure about the naming convention.

2021-01-26 01:13 UTC, kenjis commented
@MGatner What do you mean by `supporting the CodeIgniter 3 direct access method`?

I thought PagerRenderer has data only for pagination rendering, so it is more flexible that the view can access all the properties inf the PagerRenderer.

But in my use case, I don't need all the properties.
I'm migrating CI3 app to CI4, and `default_full.php` has became like this:
```php
<?php

/**
 * @var \CodeIgniter\Pager\PagerRenderer $pager
 */

$pager->setSurroundCount(2);
?>

<p class="pagination">
<?php if ($pager->hasPreviousPage()) : ?>
    <?php if ($pager->current !== 2) : ?>
    <a href="<?= $pager->getFirst() ?>" data-ci-pagination-page="<?= $pager->first ?> rel="start">&laquo;<?= lang('Pager.first') ?></a>
    <?php endif ?>

    <a href="<?= $pager->getPreviousPage() ?>" data-ci-pagination-page="<?= $pager->current - 1 ?>" rel="prev">&lt;</a>
<?php endif ?>

<?php foreach ($pager->links() as $link) : ?>
<?php if ($link['active']) : ?>
    <strong><?= $link['title'] ?></strong>
<?php else : ?>
    <a href="<?= $link['uri'] ?>" data-ci-pagination-page="<?= $link['title'] ?>">
        <?= $link['title'] ?>
    </a>
<?php endif ?>
<?php endforeach ?>

<?php if ($pager->hasNextPage()) : ?>
    <a href="<?= $pager->getNextPage() ?>" data-ci-pagination-page="<?= $pager->current + 1 ?>" rel="next">&gt;</a>

    <?php if ($pager->current !== ($pager->last - 1)) : ?>
    <a href="<?= $pager->getLast() ?>" data-ci-pagination-page="<?= $pager->last ?>"><?= lang('Pager.last') ?>&raquo;</a>
    <?php endif ?>
<?php endif ?>
</p>
```

2021-01-26 12:53 UTC, MGatner commented
This class is very confusing because "first", "last", "current" etc are used interchangeably for page numbers and for URIs. I think we might do better to differentiate those, so instead of having `$pager->first` (number) and `$pager->getFirst()` (URL) we have some clearer accessors.

2021-01-27 05:49 UTC, kenjis commented
How about these?
```
getFirstPageNumber()
getCurrentPageNumber()
getLastPageNumber()
```

2021-01-30 00:51 UTC, kenjis commented
I take down this PR.
To make all properties readable is too open. 
https://github.com/codeigniter4/CodeIgniter4/blob/49520c7862ab7ce42bb7da54df89a04e33d49fa1/system/Pager/PagerRenderer.php#L45

I sent another PR: #4188

2021-01-30 00:51 UTC, closed without merging