[Dev] Database Live Tests should depart from using deprecated CIDatabaseTestCase
codeigniter4/CodeIgniter4 pull request #4354
Opened 2021-02-26 04:21 UTC by Instrye

Do #4351

use `DatabaseTestTrait` instead `CIDatabaseTestCase`

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2021-02-26 04:23 UTC, Instrye commented
Hope someone can update the guide,

2021-02-27 12:58 UTC, MGatner requested changes
Missed one! This is a great step, User Guide should follow at some point.

2021-02-27 12:58 UTC, MGatner commented on admin/module/tests/_support/DatabaseTestCase.php
> +class DatabaseTestCase extends \CodeIgniter\Test\CIUnitTestCase
It looks like you got most of these but missed this one. 
```suggestion
class DatabaseTestCase extends CIUnitTestCase
```

2021-02-28 18:45 UTC, MGatner commented
@Instrye Please see my comment, and you will need to rebase off the recent Rector changes to **tests/**.

2021-03-01 02:59 UTC, closed without merging