Update/urlHelperTest.php
codeigniter4/CodeIgniter4 pull request #4388
Opened 2021-03-04 13:11 UTC by totoprayogo1916

**Description**
- remove `helper('text')` , which is already running on the `mb_url_title()`
- Use Factories

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

2021-03-05 12:43 UTC, MGatner requested changes

2021-03-05 12:43 UTC, MGatner commented on tests/system/Helpers/URLHelperTest.php
> -		helper('text');
Why were these removed?

2021-03-05 12:43 UTC, MGatner commented on tests/system/Helpers/URLHelperTest.php
> -		helper('text');
Why were these removed?

2021-03-05 12:49 UTC, MGatner commented on tests/system/Helpers/URLHelperTest.php
> -		helper('text');
Oh nevermind I just read your comment! Good catch.

2021-03-05 12:49 UTC, MGatner approved these changes

2021-03-05 12:50 UTC, MGatner commented
I'm not sure what is happening with the tests but I don't think it is related to the PR content. Rerunning just to check.

2021-03-05 13:08 UTC, totoprayogo1916 commented
The tests still error but
on my fork, the test passed.

2021-03-08 12:57 UTC, paulbalandan commented
Please rebase.

2021-03-08 15:08 UTC, paulbalandan approved these changes

2021-03-08 15:09 UTC, merged