The getVar method is compatible with version 4.0.4
codeigniter4/CodeIgniter4 pull request #4493
Opened 2021-03-26 03:35 UTC by lenuse

The getVar method is compatible with version 4.0.4 #4381 

**Description**
In the current version, when the request is the get method and the content-type is json, the $_REQUEST parameter cannot be obtained 

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

---------Remove from here down in your description----------

**Notes**
- Increase the length of the judgment body 
- Add unit tests under json and get methods

2021-03-26 11:58 UTC, MGatner requested changes
This looks good. A few style changes. I would also like @luispastendev to take a look since he was involved in the original discussion, as well as anyone else on the team who might know more about this than me.

2021-03-26 11:58 UTC, MGatner commented on system/HTTP/IncomingRequest.php
> +		if (strpos($this->getHeaderLine('Content-Type'), 'application/json') !== false && !is_null($this->body))
```suggestion
		if (strpos($this->getHeaderLine('Content-Type'), 'application/json') !== false && ! is_null($this->body))
```

2021-03-26 11:58 UTC, MGatner commented on tests/system/HTTP/IncomingRequestTest.php
> +		$request->setHeader('Content-Type', 'application/json');
```suggestion
		$config          = new App();
		$config->baseURL = 'http://example.com/';

		// GET method
		$_REQUEST['foo']  = 'bar';
		$_REQUEST['fizz'] = 'buzz';

		$request = new IncomingRequest($config, new URI('http://example.com/path?foo=bar&fizz=buzz'), 'php://input', new UserAgent());
		$request = $request->withMethod('GET');

		// JSON type
		$request->setHeader('Content-Type', 'application/json');
```

2021-03-26 16:55 UTC, luispastendev commented
@MGatner , take a look at a previous installation of codeigniter and observe that the getVar code was touched to support JSON requests, in this case I suppose it is fine because if the empty body was sent it generated an error.

On the other hand browsing the internet to the RFCs 7230-7237 specification nothing is mentioned about not sending body by get, in my opinion I suppose it is fine.

See the highest rated answer:
https://stackoverflow.com/questions/978061/http-get-with-request-body

2021-04-05 04:53 UTC, samsonasik approved these changes

2021-04-05 05:04 UTC, paulbalandan approved these changes

2021-04-05 09:55 UTC, merged

2021-04-05 09:56 UTC, samsonasik commented
Thank you @lenuse

2021-04-06 17:25 UTC, iRedds commented
I believe that if an empty body is sent with a Content-Type: application/json header then an exception should be thrown.

2021-04-07 01:27 UTC, lenuse commented
> I believe that if an empty body is sent with a Content-Type: application/json header then an exception should be thrown.

The getVar method is to get the json body or $_RESQUEST parameter. If the body is empty, an exception is returned and $_REQUEST will not be obtained. If the request API does not use the resetful style, the value of $_REQUEST will be used.

2021-10-17 20:03 UTC, shantiwebsolution commented
is this merged with master ? do I get updated code via composer update ?

2021-10-18 00:06 UTC, kenjis commented
@shantiwebsolution 
Yes.
Please ask support questions on our [forum](https://forum.codeigniter.com/forum-30.html).