Debug/Toolbar - Memory issue fix
codeigniter4/CodeIgniter4 pull request #4590
Opened 2021-04-20 12:23 UTC by najdanovicivan

**Description**
This is the very simple method to avoid memory leak issue #4137 when entity objects with circular references are passed to the view. 

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [  ] Unit testing, with >80% coverage
- [  ] User guide updated
- [x] Conforms to style guide

2021-04-21 12:31 UTC, MGatner requested changes
I like the concept but not the end result. We need to find some way to catch as much as we can. Does Kint (already included) not have some solution for this in place?

2021-04-21 12:31 UTC, MGatner commented on system/Debug/Toolbar.php
> +	protected function processVar($var)
Let's make this private for now, unless there are compelling reasons to allow access to this method.

2021-04-21 12:31 UTC, MGatner commented on system/Debug/Toolbar.php
> +			$var = is_callable([$var, 'toArray']) ? $var->toArray() : get_class($var);
This no longer a) tells us the object class for array-ables nor b) allows displaying valid, non-recursive objects that are not array-able.

2021-04-22 10:34 UTC, najdanovicivan commented
@MGatner  I managed to make Kint work inside debug bar. The issue I had is that Kint render will return JS and CSS in as the string and since those are set as text via JS. The javascript from Kint will never be executed. So I had to play a bit with it to add the JS and CSS into the page head instead and then drop those when it's being rendered in the debug bar

2021-04-22 11:48 UTC, MGatner commented
I'll take a look - if it is working then that's probably good. Kint also supports prefix modifiers to adjust the behavior - I think we could probably use `~` for "text output", or maybe `@` to "return output". Play around with those and see what you think. 

https://kint-php.github.io/kint/advanced/

2021-04-22 11:51 UTC, MGatner requested changes
I think this should be fine. It definitely adds some complexity. See what you think of the text output option and if that is a worthy trade-off.

2021-04-22 11:51 UTC, MGatner commented on system/Debug/Toolbar.php
> +			$kintScirpt         = substr($kintScirpt, 0, strpos($kintScirpt, '</style>') + 8 );
```suggestion
			$kintScript         = substr($kintScript, 0, strpos($kintScirpt, '</style>') + 8 );
```
Typo in the variable name.

2021-04-22 11:51 UTC, MGatner commented on system/Debug/Toolbar.php
> +			$kintScirpt         = @Kint::dump('');
Ah, I see you already found the `@`.

2021-04-22 11:51 UTC, MGatner commented on system/Debug/Toolbar.php
> +					. $kintScirpt
```suggestion
					. $kintScript
```

2021-04-22 11:52 UTC, najdanovicivan commented
I am using @ prefix to return output. I tried text output as well but it looks nasty.  

I was unable to make it work by chaining prefixes eg @~dd() will not work for me. 

Another problem with text output is it can get very long especially when controller is being passed to the view and if any of the variables contains HTML it may break the <pre> tag

2021-05-02 12:54 UTC, MGatner approved these changes

2021-05-02 12:55 UTC, merged