Optimize CommandRunner and Commands
codeigniter4/CodeIgniter4 pull request #4683
Opened 2021-05-13 17:31 UTC by paulbalandan

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] Conforms to style guide

2021-05-14 07:47 UTC, paulbalandan commented
@MGatner this optimization made all test cases of `CommandRunnerTest` to be all under 0.50 s.

2021-05-14 11:43 UTC, MGatner requested changes
Glad you cracked this egg! Moving the discovery to the constructor could cause some people problems, but generally I think it is a better design. Maybe see if we can get another review from @lonnieezell or @samsonasik on that point? Otherwise just a couple of tweaks.

2021-05-14 11:43 UTC, MGatner commented on system/CLI/CommandRunner.php
> +		$command = $command ?? 'list';
```suggestion
 		$command = array_shift($params) ?? 'list';
```

2021-05-14 11:43 UTC, MGatner commented on system/CLI/Commands.php
> +		$locator = Services::locator();
Lonnie wants us to start using the helper function. 
```suggestion
		$locator = service('locator');
```

2021-05-14 11:43 UTC, MGatner commented on tests/system/CLI/CommandRunnerTest.php
> +		self::$logger = Services::logger();
```suggestion
		self::$logger = service('logger');
```

2021-05-14 11:43 UTC, MGatner commented on tests/system/CLI/CommandRunnerTest.php
> +		self::$runner->initController(Services::request(), Services::response(), self::$logger);
Service helper

2021-05-14 13:15 UTC, lonnieezell commented
I typically prefer not to do things like that in a constructor but in this case I don't see a problem with it. Commands aren't something that are called all of the time, and testing is where that has the tendency to be the biggest issue. But that's why we're moving it now so it looks good to me!

2021-05-16 13:10 UTC, paulbalandan commented
> Glad you cracked this egg! Moving the discovery to the constructor could cause some people problems, but generally I think it is a better design. Maybe see if we can get another review from @lonnieezell or @samsonasik on that point? Otherwise just a couple of tweaks.

I have pondered on this and I don't think moving discovery to the constructor would give us problems. Discovery essentially fills up the $commands array prop with the discovered commands. Current design shows that every invoke of run we call discoverCommands which in turn returns early if the $commands prop is already populated. So this prop is never overwritten. Moving the discovery at constructor initialization would be a big gain, as the tests demonstrate.

2021-05-17 06:13 UTC, samsonasik approved these changes

2021-05-17 13:16 UTC, MGatner approved these changes

2021-05-17 13:16 UTC, merged