Document new coding style guide
codeigniter4/CodeIgniter4 pull request #4825
Opened 2021-06-11 17:00 UTC by paulbalandan

**Description**
Start documenting the new coding style rules and conventions. Most of here are from PSR-12 with a non-exhaustive list of our "custom" rules. After this, anyone can contribute adding to the customized rules section basing upon our enforced CS.

**Checklist:**
- [x] Securely signed commits

2021-06-14 15:05 UTC, MGatner requested changes
This is awesome! Thanks for being so thorough. One inline comment.

2021-06-17 16:41 UTC, sfadschm commented on contributing/styleguide.md
> +_portions therein not included herein SHOULD be read as if included herein._
I guess it means that even if we do not copy all rules of PSR-12 to our styling guide documentation explicitly, such (uncopied) rules still apply.

2021-06-17 16:46 UTC, paulbalandan commented on contributing/styleguide.md
> +_portions therein not included herein SHOULD be read as if included herein._
🤦‍♂️ Sorry, guys. The legalese took over on that part. And yes, @sfadschm  is right. 😅

2021-08-12 03:22 UTC, lonnieezell commented
@paulbalandan is this ready to merge?

2021-09-03 05:41 UTC, kenjis commented on contributing/styleguide.md
> +_portions therein not included herein SHOULD be read as if included herein._
@paulbalandan 
How about this?
```
_Even if we do not copy all rules of [PSR-12][psr12] to this coding styling guide explicitly, such uncopied rules still apply._
```

2021-09-04 01:25 UTC, kenjis approved these changes

2021-09-04 12:10 UTC, MGatner requested changes
Could we get a link to the repo with a very general description?

2021-09-04 14:17 UTC, paulbalandan commented
> Could we get a link to the repo with a very general description?

I think I did not follow what you want ?

2021-09-05 11:52 UTC, MGatner commented
I would like some mention that the coding style is enforced by CS Fixer, with a link to the CodeIgniter/style-guide repo and a one-sentence introduction on what this is/does. I can suggest the change when I'm on desktop later if that would be helpful.

2021-09-07 02:02 UTC, kenjis commented
@MGatner v4.1.4 was released. Why don't you merge this for now?

2021-09-08 13:30 UTC, MGatner commented
Yes this needs to get in - I will make that addition today.

2021-09-08 14:05 UTC, MGatner requested changes
Feel free to emend, but this is the kind of addition I would like to see.

2021-09-08 14:05 UTC, MGatner commented on contributing/styleguide.md
> +
```suggestion
## Implementation

Our team uses [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) to apply coding standard fixes automatically. If you would like to leverage these tools yourself visit the [Official CodeIgniter Coding Standard](https://github.com/CodeIgniter/coding-standard) repository for details.

```

2021-09-08 22:45 UTC, MGatner approved these changes

2021-09-08 23:44 UTC, merged