Fix getVar() method when trying to get JSON variable that does not exists
codeigniter4/CodeIgniter4 pull request #4909
Opened 2021-07-04 09:36 UTC by michalsn

**Description**
Fixes #4906

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage
- [x] Conforms to style guide

2021-07-04 12:20 UTC, paulbalandan approved these changes

2021-07-04 12:24 UTC, MGatner requested changes
Nice fix. Quick hardening of assertions.

2021-07-04 12:24 UTC, MGatner commented on tests/system/HTTP/IncomingRequestTest.php
> +        $this->assertSame(null, $request->getJsonVar('notExists'));
```suggestion
        $this->assertNull($request->getJsonVar('notExists'));
```

2021-07-04 12:24 UTC, MGatner commented on tests/system/HTTP/IncomingRequestTest.php
> +        $this->assertSame(null, $request->getVar('notExists'));
```suggestion
        $this->assertNull($request->getVar('notExists'));
```

2021-07-04 19:55 UTC, michalsn commented
The failing test is irrelevant to the PR.

2021-07-05 12:08 UTC, MGatner approved these changes

2021-07-05 12:08 UTC, merged