Fix bug with DB-Forge composite foreign keys - Change branch base
codeigniter4/CodeIgniter4 pull request #4932
Opened 2021-07-13 17:40 UTC by monkenWu

**Description**
Fixes #4310 
Original PR #4931 

Change the branch base to 4.2.

I edited the `addForeignKey` method and `_processForeignKeys` method of `CodeIgniter\Database\Forge` so that they can define composite foreign keys in an array.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

2021-07-23 07:28 UTC, michalsn requested changes
This looks good. 

I was wondering if it would be better to leave the string casting in `addForeignKey()` method and parse the variables, but using arrays is more natural in this case. I don't think many developers have extended this method so chances that this will break someone's code are low.

I'm fine with these changes, but since we're removing casting in the public method for some variables, please mention this in the changelog (https://github.com/codeigniter4/CodeIgniter4/tree/4.2/user_guide_src/source/changelogs - you will have to create a new file `v4.2.0.rst`). We don't wanna surprise anyone.

2021-07-23 08:48 UTC, monkenWu commented
@michalsn  Thanks for the review.
In fact, I refer to the method `addKey()`, which accepts both string and array. Therefore, I also continued this pattern in `addForeignKey()`.
![擷取](https://user-images.githubusercontent.com/55150513/126758458-1cb761fa-3ff5-49cf-8f0c-c27310b6688d.PNG)

I will create a new `v4.2.0.rst` file soon and mention this change in `Enhancements`.

2021-07-23 11:01 UTC, paulbalandan commented
Please rename your last commit to something else. We're not releasing yet.

2021-07-23 11:11 UTC, paulbalandan commented on system/Database/Forge.php
> +            throw new DatabaseException(lang('Database.fieldNotExists', $errorNames));
If the count > 1, the array's first element will only be translated to the exception message. The others would be disregarded. I think you need to call implode here and adjust the message for singular and plural fields.

2021-07-23 11:11 UTC, paulbalandan commented on system/Database/Forge.php
> +            throw new DatabaseException(lang('Database.fieldNotExists', $errorNames));
Please add a test showing that adding unknown fields will throw an exception.

2021-07-27 14:11 UTC, monkenWu commented
@paulbalandan  I fixed the composition foreign keys exception and added a new test case

2021-08-12 03:05 UTC, lonnieezell commented
@michalsn are you able to review these changes?

2021-08-17 17:35 UTC, michalsn approved these changes
Thanks @monkenWu it looks good!

One last thing - you have to rebase to resolve conflicts. If you have never done this before, here is a nice instruction: https://samsonasik.wordpress.com/2015/09/16/practical-git-4-rebasing-conflicted-task-branch-against-primary-branch/

2021-08-18 05:29 UTC, paulbalandan commented on tests/system/Database/Live/ForgeTest.php
> +            $this->assertSame($foreignKeyData[1]->sequence, 1);
In `assertSame` the expected values should come first before the tested values.

2021-08-18 05:29 UTC, paulbalandan commented on tests/system/Database/Live/ForgeTest.php
> +            $this->assertSame($foreignKeyData[0]->constraint_name, $this->db->DBPrefix . 'forge_test_invoices_users_id_users_second_id_foreign');
Same

2021-08-18 05:29 UTC, paulbalandan commented on tests/system/Database/Live/ForgeTest.php
> +            $this->assertSame($foreignKeyData[$secondIdKey]->constraint_name, $this->db->DBPrefix . 'forge_test_invoices_users_id_users_second_id_foreign');
Same

2021-08-18 05:29 UTC, paulbalandan commented on tests/system/Database/Live/ForgeTest.php
> +
Same

2021-08-18 07:36 UTC, paulbalandan approved these changes

2021-08-23 05:54 UTC, paulbalandan commented
@monkenWu can you do a last minute rebase to fix the merge conflicts before we can merge this?

2021-08-23 09:45 UTC, paulbalandan approved these changes

2021-08-23 09:45 UTC, merged