Curl scalars 4.2
codeigniter4/CodeIgniter4 pull request #4953
Opened 2021-07-20 13:35 UTC by nowackipawel

Each pull request should address a single issue and have a meaningful title.

**Description**
Explain what you have changed, and why.

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

---------Remove from here down in your description----------

**Notes**
- Pull requests must be in English
- If the PR solves an issue, reference it with a suitable verb and the issue number
(e.g. fixes <hash>12345)
- Unsolicited pull requests will be considered, but there is no guarantee of acceptance
- Pull requests should be from a feature branch in the contributor's fork of the repository
  to the develop branch of the project repository

2021-07-21 11:49 UTC, MGatner requested changes
Looking better! Still need tests.

2021-07-21 11:49 UTC, MGatner commented on system/HTTP/CURLRequest.php
> +                    $this->setHeader($name, $value);
Is there any reason to include stringables?
```suggestion
                if (is_scalar($value) || (is_object($value) && method_exists($value, '__toString')) {
                    $this->setHeader($name, (string) $value);
```

2021-07-21 11:52 UTC, nowackipawel commented
@MGatner in this case I would say we need to add label "help needed". :(.
I would love to write tests as I did  year or two ago, but at the moment hard to find time for that kinda things :(.

2021-08-12 03:03 UTC, lonnieezell commented
> I would love to write tests as I did year or two ago, but at the moment hard to find time for that kinda things :(.

@nowackipawel  We all completely understand time constraints. We are all volunteers stealing  time from the rest of our life to work on this. These look like good changes. Is there no way you can take a little time to learn testing? There's a better chance of getting changes in (of which you've had quite a few good suggestions over the years) if you can do the testing. Otherwise you're asking us to take time from what we see as needs to test your code. And we all have limited time to work on this.

2021-09-08 23:21 UTC, kenjis commented
It seems the base branch of this PR must be changed to `develop`.

2021-10-18 00:15 UTC, kenjis commented
@nowackipawel 
There are conflicts.

Could you rebase your branch?
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#pushing-your-branch

2022-01-21 03:47 UTC, paulbalandan commented
Hi, and thanks for your contribution! As this PR has been standing for a couple of months now and no effort has been seen to add the necessary unit testing to confirm the patch, we can conclude that there's no more interest in moving this forward.

We love to see and appreciate all contributions coming in from the community. However, please make it an effort to make it easy for maintainers to verify your code (that you want to be part of the framework core) through unit testing. You cannot (and we cannot, either) expect to write only source code and delegate the testing part to others. Unfortunately, that's not how OSS works.

Closing this for now. We'd still love to see you around contributing to the framework. Feel free to open a new PR once all necessary testing is in place. Thanks!

2022-01-21 03:47 UTC, closed without merging