Model - Fix zero value primary key
codeigniter4/CodeIgniter4 pull request #4975
Opened 2021-07-28 13:19 UTC by najdanovicivan

**Description**
Primary key in SQL can have value of 0 or empty string. This modifies the model to use isset to handle such values instead of doing an empty check so that rows which such keys can be inserted/updated in the DB

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2021-07-29 03:00 UTC, paulbalandan commented on system/Model.php
> +                && isset($data->{$this->primaryKey}))) {
```suggestion
        if (
            method_exists($data, 'toRawArray')
            && (! empty($properties) && ! empty($this->primaryKey)
            && ! in_array($this->primaryKey, $properties, true)
            && isset($data->{$this->primaryKey}))
        ) {
```

2021-07-29 12:47 UTC, MGatner requested changes
Please add some tests for primary keys of '', 0, '0', false, and 'false'. 

Also while you're here, can we replace those two awful composite `if` statements with a static function? Something like `getObjectPrimaryKey()`

2021-08-12 02:55 UTC, lonnieezell commented
@najdanovicivan are you able to make these changes? If not, I'm closing.

2021-08-12 14:47 UTC, najdanovicivan commented
I’m on it.

2021-08-12 19:32 UTC, najdanovicivan commented
@MGatner we already have getIdValue() method so I've used it in place of those `if` statements

Regarding the other place where we have those nasty `if` statements it is a deprecated static method and because it's static we cannot call getIdValue() there so I left it unchanged is should be removed in future releases anyway

I also added couple of tests.  I haven't worked with DataBase test before on CI so it took me a while to figure it out how those work.

2021-08-12 23:24 UTC, najdanovicivan commented
I'm not sure what's going on with test on 4.2 branch some of them are failing.  

What I also see now that MSSQL, SQLite and Postgres behave differently with empty values

2021-08-13 13:26 UTC, MGatner commented
It looks like the failing tests are related to the way soft deletes are handled with primary keys. I'm on mobile so I can't dig very far right now, but some other tests might need changing for this to work. 

In general we have a few open issues/PRs around boolean/empty values in the database layer. I think these will all need to be pulled together and a final decision made on how to handle things before `4.2` will be predictably consistent.

2021-09-08 22:45 UTC, MGatner commented
`4.2` branch has been rebased and merged into `develop`! Those outstanding changes should all be in place - @najdanovicivan could you rebase this and point it back to `develop`? That should give us a good idea of what remains to be fixed.

2021-09-11 12:43 UTC, MGatner commented
Tests are still failing.

2022-01-23 08:06 UTC, paulbalandan commented
I am seeing no progress in this since September. Please open a new PR with updated code where tests are passing.

2022-01-23 08:06 UTC, closed without merging