(Paging) Ensure page validity
codeigniter4/CodeIgniter4 pull request #5125
Opened 2021-09-24 12:55 UTC by puschie286

An invalid page lead to an exception when using the model paginate function.
page::store validates the page but it doesnt update the page used in the model.

So we need to read the page value again after calling pager::store in paginate

2021-09-24 13:05 UTC, paulbalandan requested changes
It seems you are overriding the `$page` variable in L1082 for the computation of `$offset`. Can you add some tests to cover this?

2021-09-24 14:23 UTC, puschie286 commented
@paulbalandan something like this ?
not sure why the PHP CS Fixer keeps failing...

2021-09-24 17:46 UTC, mostafakhudair requested changes
This may fix CS Fixer failure

2021-09-24 17:46 UTC, mostafakhudair commented on tests/system/Models/PaginateModelTest.php
> +    	$this->model->paginate(1,'default', -500);
```suggestion
    	$this->model->paginate(1, 'default', -500);
```

2021-09-24 17:46 UTC, mostafakhudair commented on tests/system/Models/PaginateModelTest.php
> +    	$this->assertSame($this->model->pager->getPageCount(),$this->model->pager->getCurrentPage());
```suggestion
    	$this->assertSame($this->model->pager->getPageCount(), $this->model->pager->getCurrentPage());
```

2021-09-24 17:46 UTC, mostafakhudair commented on tests/system/Models/PaginateModelTest.php
> +    {
```suggestion
    public function testPaginatePageOutOfRange(): void
    {
```

2021-09-24 17:49 UTC, mostafakhudair commented on tests/system/Models/PaginateModelTest.php
> +    }
```suggestion

    public function testPaginatePageOutOfRange(): void
    {
        $this->createModel(ValidModel::class);
        $this->model->paginate(1, 'default', -500);
        $this->assertSame(1, $this->model->pager->getCurrentPage());
        $this->model->paginate(1, 'default', 500);
        $this->assertSame($this->model->pager->getPageCount(), $this->model->pager->getCurrentPage());
    }
```

2021-09-24 17:53 UTC, mostafakhudair commented on system/BaseModel.php
>          $offset      = ($page - 1) * $perPage;
```suggestion
        $perPage     = $this->pager->getPerPage($group);
        $offset      = ($pager->getCurrentPage($group) - 1) * $perPage;
```

2021-09-25 04:04 UTC, kenjis commented
@puschie286 Please run `composer cs-fix` to fix coding style.

2021-10-05 03:31 UTC, lonnieezell approved these changes

2021-10-05 03:31 UTC, merged