Fix highlighting in database debug toolbar
codeigniter4/CodeIgniter4 pull request #5129
Opened 2021-09-25 03:30 UTC by vlakoff

Highlighting wasn't working for multiple-word terms, as they were searched in the SQL string with nbsp entities instead of regular spaces.

This code could be optimized, though it's not crucial as it's a debug function.

2021-09-25 03:46 UTC, vlakoff commented
Added a commit implementing replacement using regexp with word boundaries, to avoid overlaps / false positives with strings such as "OR", "IN"…

2021-09-25 07:48 UTC, sfadschm commented
Can you add before/after schreenshots?

2021-09-25 10:39 UTC, paulbalandan commented on system/Database/Query.php
> +        /** @noRector \Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector */
I would agree with Rector here to simplify the return. Besides, our coding standard also includes this rule to simplify the return when possible (although it is not taking effect here).

2021-09-26 09:22 UTC, vlakoff commented
I confirmed the fix, but if ever you want screenshots of this toolbar content, you may have a look at #5136.

2021-09-26 10:41 UTC, sfadschm commented
> I confirmed the fix, but if ever you want screenshots of this toolbar content, you may have a look at #5136.

There is unfortunately none of the key words changed here visible in the other PR. Would be great to see just one example what has been fixed in this PR, too.

2021-09-28 02:11 UTC, paulbalandan requested changes
Since this PR addresses an error in highlighting multiple-word identifiers, please add before/after screenshots, as @sfadschm suggested, that show there are indeed problems with the current and how this PR fixes them.

2021-09-29 16:31 UTC, vlakoff commented
Before:
![5129-before](https://user-images.githubusercontent.com/544424/135310611-d938b39d-67a5-459e-82fe-30e0affa6164.png)

After:
![5129-after](https://user-images.githubusercontent.com/544424/135310633-d9e135ce-2133-4b72-a603-c3252f0cab30.png)

2021-09-29 16:42 UTC, vlakoff commented
Maybe we should add the ASC and DESC keywords?

2021-09-29 16:56 UTC, vlakoff commented
Also, I'd suggest either highlighting commas in addition to parentheses, or not highlighting parentheses. Your pick?

2021-09-29 17:16 UTC, sfadschm commented
I think adding the keywords would be good, but would rather remove the parentheses. But lets wait for other calls.

2021-09-29 23:09 UTC, kenjis commented
I would like removing parentheses, adding ASC and DESC.

2021-09-29 23:29 UTC, paulbalandan commented
Let's highlight only keywords, leaving out parentheses and other punctuation marks.

2021-09-30 22:47 UTC, vlakoff commented
* Removed the highlighting of parentheses
* Added ASC and DESC keywords
* Reduced the number of commits by removing the commits related to the Rector warning

2021-10-01 00:46 UTC, paulbalandan approved these changes

2021-10-03 03:56 UTC, merged

2021-10-03 03:56 UTC, paulbalandan commented
Thank you, @vlakoff