Convert bug report to new syntax
codeigniter4/CodeIgniter4 pull request #5264
Opened 2021-10-31 12:19 UTC by paulbalandan

**Description**
Closes #4944 

**Checklist:**
- [x] Securely signed commits

2021-10-31 12:28 UTC, MGatner requested changes
This is awesome! Thanks for tackling this - it's been on my mind for a while but just never sat down with the file format. A few comments...

2021-10-31 12:28 UTC, MGatner commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +  - type: input
Should this be a dropdown? There are only a few options right?

2021-10-31 12:28 UTC, MGatner commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: Which operating systems have you used?
```suggestion
      label: Which operating systems have you tested for the bug?
```

2021-10-31 12:28 UTC, MGatner commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: Which SAPI did you use?
Will people understand SAPI? Would "web server software" or something be more clear?

2021-10-31 12:28 UTC, MGatner commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: 'Expected Output'
Quoting on labels is inconsistent. I'm not sure if it matters.

2021-10-31 22:36 UTC, sfadschm commented
Why is there two descriptions asking for the expected behavior?
Lines 73 and 88.

2021-10-31 22:52 UTC, kenjis commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: Also tell us, what did you expect to happen?
This should ask only what happened. 

Not to be expected to happen.
It is asked in `Expected Output`.

2021-11-01 00:19 UTC, MGatner reviewed
I agree with Kenji's change, then this is ready IMO.

2021-11-01 05:23 UTC, kenjis approved these changes

2021-11-01 05:24 UTC, merged

2021-11-01 05:29 UTC, paulbalandan commented
I'll be pushing a direct commit. There's a typo

```
There is a problem with this template

body[1]: dropdowm is not a valid input type. Learn more.
```

2021-11-01 05:34 UTC, kenjis commented
Where did you get the error message?
There is no new Issue form, I was looking for why.

2021-11-01 05:39 UTC, paulbalandan commented
In the file itself, there is a validation message.

2021-11-01 05:40 UTC, paulbalandan commented
The new issue form looks savvy. 🎉