Fix deprecated usage of `null` on `string` params of internal functions
codeigniter4/CodeIgniter4 pull request #5371
Opened 2021-11-21 10:38 UTC by paulbalandan

**Description**
Related to #4883

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2021-11-21 13:19 UTC, MGatner requested changes
Only one I didn't look very closely at is `Time`, I can revisit if you get two other reviews.

2021-11-21 13:19 UTC, MGatner commented on system/Database/Postgre/Connection.php
> +        if (! empty($port) && ctype_digit($port)) {
```suggestion
        if ($port !== '' && ctype_digit($port)) {
```
Not sure if `'0'` is significant here?

2021-11-21 13:19 UTC, MGatner commented on system/Validation/Rules.php
> -        // Break the table and field apart
I find these comments helpful.

2021-11-22 09:49 UTC, kenjis commented on system/Validation/FormatRules.php
> -     * @param string $which IP protocol: 'ipv4' or 'ipv6'
This phpdoc is helpful.

2021-11-22 09:50 UTC, kenjis commented on system/Validation/Rules.php
> -     * @param array  $data Other field/value pairs
This phpdoc is helpful.

2021-11-22 09:56 UTC, kenjis commented on system/Validation/Validation.php
> -            // so there will always be a string being returned.
This comment is helpful.

2021-11-22 09:57 UTC, kenjis commented on system/Validation/Validation.php
> -        // passed along from a redirect_with_input request.
This comment is helpful.

2021-11-22 10:00 UTC, kenjis commented on system/Validation/Rules.php
> -        // search field is present or not.
This comment is helpful.

2021-11-22 10:01 UTC, kenjis commented on system/Validation/Rules.php
> -        // as $fields is the lis
This comment is helpful.

2021-11-22 10:01 UTC, kenjis commented on system/Validation/Rules.php
> -        // search field is present or not.
This comment is helpful.

2021-11-22 10:01 UTC, kenjis commented on system/Validation/Rules.php
> -        // any of the fields are not present in $data
This comment is helpful.

2021-11-23 01:36 UTC, kenjis approved these changes

2021-11-24 12:53 UTC, MGatner approved these changes

2021-11-25 00:00 UTC, merged