fix: Incorrect type `BaseBuilder::$tableName`
codeigniter4/CodeIgniter4 pull request #5378
Opened 2021-11-24 01:38 UTC by kenjis

**Description**
Fixes #4457
- make sure `$this->tableName` is string

`$this->tableName` is used only in `BaseBuilder::getTable()`.
`BaseBuilder::getTable()` is used only in `Model::builder()`:
https://github.com/codeigniter4/CodeIgniter4/blob/b8fe16d2ff708971693a5e3325b74447ffb93fdd/system/Model.php#L524

`$table` or `$this->table` in the `Model` is a single table name without an alias.
So the above code is just to make sure that `$table` and the Builder's table name are the same or not.
If these are the same table, it returns existing `$this->builder`.

In other words, if the Builder's table name is not a single table, these are always not the same.

Therefore `BaseBuilder::getTable()` does not have to return array or multiple table string like `'tableA, tableB'`.
Returning empty string is enough.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2021-11-24 12:59 UTC, MGatner requested changes
I think this is a fine fix for a messy situation. Definitely need to revisit this in version 5. Please add a note to the changelogs on the off chance someone was using this, and link this PR or issue to our version 5 project column.

2021-11-26 00:39 UTC, kenjis commented
@MGatner Is there any chance to include this PR in the next version (4.1.6)?

I created a more aggressive PR #5387 for v5.0.
It's kind of a memo to remember my current thoughts.

Added a note in the project Version 5.

2021-11-26 13:11 UTC, MGatner commented
@kenjis I think that is a good approach but I would still like a note in the changelogs, something like this:

> Multiple table names will no longer be stored in `BaseBuilder::$tableName` - an empty string will be used instead.

2021-11-27 01:58 UTC, kenjis commented
@MGatner I added in the changelog.

2021-11-27 12:47 UTC, MGatner approved these changes

2021-11-27 12:47 UTC, MGatner commented
Thank you!

2021-12-01 03:48 UTC, merged