docs: fix environments.rst
codeigniter4/CodeIgniter4 pull request #5476
Opened 2021-12-17 06:24 UTC by kenjis

**Description**
- remove environment-specific configuration files 

It seems there is no such a thing in CI4.

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [] Conforms to style guide

2021-12-18 13:07 UTC, MGatner requested changes

2021-12-18 13:07 UTC, MGatner commented on user_guide_src/source/general/environments.rst
>  Conversely, setting the constant to 'production' will disable all error
```suggestion
Conversely, setting the constant to ``production`` will disable all error
```

2021-12-18 13:07 UTC, MGatner commented on user_guide_src/source/general/environments.rst
> -:doc:`Working with Configuration Files </general/configuration>` documentation.
Why was this removed? Does that section not exist?

2021-12-18 13:10 UTC, MGatner commented
I see now, we don't have such a thing as "Environment-specific configuration files". Boot files are the closest thing, and those are already covered.

I agree with this removal.

2021-12-18 13:14 UTC, kenjis commented
Yes, CI3 has environment-specific configuration files, but CI4 does not have.

2021-12-19 07:01 UTC, paulbalandan approved these changes

2021-12-20 08:30 UTC, kenjis commented on user_guide_src/source/general/environments.rst
>  Conversely, setting the constant to 'production' will disable all error
Fixed.

2021-12-20 08:32 UTC, merged