fix: add missing Migration lang item
codeigniter4/CodeIgniter4 pull request #5557
Opened 2022-01-09 02:32 UTC by kenjis

**Description**
- add missing Migration lang item

```
$ php spark migrate

CodeIgniter v4.1.6 Command Line Tool - Server Time: 2022-01-08 20:30:40 UTC-06:00

すべての新しいマイグレーションを実行しています...
Done migrations.
```

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

2022-01-09 13:05 UTC, MGatner requested changes
Small semantic suggestion. 

@lonnieezell do we need to do anything to "request translators" when new strings get added, for the translations repo?

2022-01-09 13:05 UTC, MGatner commented on system/Commands/Database/Migrate.php
> +            CLI::write(lang('Migrations.done'), 'green');
```suggestion
            CLI::write(lang('Migrations.migrated'), 'green');
```

2022-01-09 13:05 UTC, MGatner commented on system/Language/en/Migrations.php
> +    'done'              => 'Done migrations.',
```suggestion
    'migrated'          => 'Migrations complete.',
```

2022-01-09 14:11 UTC, sfadschm commented
> Small semantic suggestion.
> 
> @lonnieezell do we need to do anything to "request translators" when new strings get added, for the translations repo?

Paul implemented static analysis checks in the translation repo that check for missing, duplicated or copied strings.

2022-01-09 23:38 UTC, kenjis commented
> Paul implemented static analysis checks in the translation repo that check for missing, duplicated or copied strings.

But translators do not know if they run checks.

2022-01-10 12:45 UTC, MGatner approved these changes

2022-01-10 23:19 UTC, merged