fix: slash_item() errors when asked for a configuration item which doesn't exist #5967
codeigniter4/CodeIgniter4 pull request #5973
Opened 2022-05-07 21:34 UTC by aletoropov

**Description**
Check object property which doesn't exist

Related #5967

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2022-05-07 23:53 UTC, kenjis commented
Thank you for sending this PR!

See GitHub Action checks.
1. Please fix coding style.
2. Please fix the production code to pass the existing tests.

And can you add a test case for this fix?

See
- https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style
- https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

2022-05-08 10:58 UTC, paulbalandan commented
Please don't use merge commits when updating your PR branch with the `develop` branch.

2022-05-08 11:54 UTC, kenjis commented
How to update your PR branch:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#syncing-develop

2022-05-09 21:20 UTC, aletoropov commented
How I can created test?

2022-05-10 00:12 UTC, kenjis commented
@aletoropov You need to learn PHPUnit and unit testing.

Unit Testing Tutorial: What is, Types, Tools & Test EXAMPLE
https://www.guru99.com/unit-testing-guide.html

PHPUnit: What, Why, How? | Andy Carter
https://andy-carter.com/blog/phpunit-what-why-how

PHP Unit Testing - PHPUnit Tutorial - Full PHP 8 Tutorial - YouTube
https://www.youtube.com/watch?v=9-X_b_fxmRM

Getting Started with Version 9 of PHPUnit – The PHP Testing Framework
https://phpunit.de/getting-started/phpunit-9.html

2022-05-10 00:17 UTC, kenjis commented
@aletoropov See https://github.com/codeigniter4/CodeIgniter4/pull/5973/commits
Your branch still has merge commits.
Could you remove these?

See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#pushing-your-branch

2022-05-10 00:56 UTC, aletoropov commented
> @aletoropov See https://github.com/codeigniter4/CodeIgniter4/pull/5973/commits Your branch still has three merge commits. Could you remove these?
> 
> See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#pushing-your-branch
I did it

2022-05-10 01:06 UTC, kenjis commented
@aletoropov Thanks!

2022-05-23 08:24 UTC, kenjis requested changes
Please fix the product code because a test failed, and add a new test for this.

```
1) CodeIgniter\CommonFunctionsTest::testSlashItem
Failed asserting that null is identical to ''.

/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/CommonFunctionsTest.php:396
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:97
```

2022-05-29 07:33 UTC, kenjis commented on tests/system/CommonFunctionsTest.php
> +        $this->assertNull(null, slash_item('cookieDomain')); // empty, so untouched
The `$cookieDomain` is empty string. The changed assertion is incorrect.
https://github.com/codeigniter4/CodeIgniter4/blob/58aa05ee8a02994bc28e631cfe5aa3130831c259/app/Config/App.php#L261

2022-05-29 07:37 UTC, kenjis commented on tests/system/CommonFunctionsTest.php
> +        $this->assertNull(null, slash_item('cookieDomain')); // empty, so untouched
`public static function assertNull($actual, string $message = ''): void`

`$this->assertNull(null)` does not make sense.

2022-06-02 20:58 UTC, closed without merging