fix: when running on CLI, two Request objects were used in the system
codeigniter4/CodeIgniter4 pull request #6089
Opened 2022-06-07 00:56 UTC by kenjis

**Description**
Fixes https://github.com/codeigniter4/CodeIgniter4/issues/6086

The current implementation has two Request objects (`IncommingRequest` and `CLIRequest`) when running on CLI.
Because some classes call `Services::request()` inside and it always returns `IncommingRequest`.

When `CLIRequest` is used in `CodeIgniter`, developers assume that the `CLIRequest` object is used system-wide.
This PR makes that so.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2022-06-07 02:54 UTC, samsonasik approved these changes

2022-06-07 11:20 UTC, MGatner reviewed
I want to think about this one a bit. On the one hand it is convenient (from a developer standpoint) to have the appropriate Request class anytime the service is called; on the other hand it complicates (from a coding standpoint) our PSR-15 layer even more.

2022-06-07 11:43 UTC, kenjis commented
Yes, we need to consider this.

2022-06-23 02:33 UTC, kenjis commented
Changed the implementation a bit.

2022-06-23 11:35 UTC, MGatner commented
I'm coming around to this. It is a bit hacky, but our current Request implementation is a mess so that might just need to be the case.

2022-06-23 12:23 UTC, kenjis commented on system/Config/Services.php
> +            $request = AppServices::incommingrequest($config);
Fixed.

2022-06-23 12:27 UTC, kenjis commented
I've been thinking about it for a while and can't think of any other way to fix it except this way in the current situation.
Any idea is welcome.

2022-06-24 10:33 UTC, MGatner commented
If you've given this plenty of thought I don't feel the need to. At this point pretty much anything would be an improvement and what you've done looks reasonable to me.

2022-06-24 10:34 UTC, MGatner approved these changes

2022-06-24 10:42 UTC, samsonasik approved these changes

2022-06-26 09:31 UTC, kenjis commented
Added changelog.

2022-06-26 11:13 UTC, MGatner requested changes
Tiny syntax changes then I'm good with this.

2022-06-26 11:13 UTC, MGatner commented on user_guide_src/source/changelogs/v4.2.2.rst
> +- Now ``CLIRequest::isCLI()`` always return true.
```suggestion
- Now ``CLIRequest::isCLI()`` always returns true.
```

2022-06-26 11:13 UTC, MGatner commented on user_guide_src/source/changelogs/v4.2.2.rst
> +- Now ``IncommingRequest::isCLI()`` always return false.
```suggestion
- Now ``IncommingRequest::isCLI()`` always returns false.
```

2022-06-26 12:29 UTC, MGatner approved these changes

2022-06-26 23:39 UTC, merged