fix: exceptionHandler may return invalid HTTP status code
codeigniter4/CodeIgniter4 pull request #6228
Opened 2022-07-04 04:19 UTC by kenjis

**Description**
Fixes #6227

The exception code has nothing to do with HTTP status code.
So it is impossible to determine HTTP status code from exception code.

- fix `Exceptions::exceptionHandler()`
- add `HasExitCodeException` and `HasHttpStatusCodeException` Interface

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

2022-07-04 05:26 UTC, iRedds commented
I have doubts about the implementation.
If it's an HTTP exception, then the code should be >= 400 and < 500. 
In all other cases, the code should be 500.

Something like this
```php
$statusCode = 500;
$exitStatus = EXIT_ERROR;

if (
    $exception instanceof HttpException
    && $exception->getCode() >= 400
    && $exception->getCode() < 500
) {
    $statusCode = $exception->getCode();    
}

There is no point in additional interfaces.
And to be honest, it's a little strange for me that HTTP exceptions are handled through Debug.
```

2022-07-06 04:15 UTC, kenjis commented
> it's a little strange for me that HTTP exceptions are handled through Debug.

Yes. This is global exception handler, so it should return 500 Response for all cases.
HTTP exceptions should be handled before here.

2022-07-09 10:02 UTC, MGatner commented
Just a note that HTTP exceptions actually include 300s as well via `RedirectException`.

2022-07-11 02:58 UTC, kenjis commented
There is `HTTPException`, but it has nothing to do with HTTP response code.
https://github.com/codeigniter4/CodeIgniter4/blob/bc688d9b99868075c2d98f701c154f5add038346/system/HTTP/Exceptions/HTTPException.php#L19

2022-07-11 04:09 UTC, kenjis commented
`RedirectException` is caught in `CodeIgniter::run()`:
https://github.com/codeigniter4/CodeIgniter4/blob/bc688d9b99868075c2d98f701c154f5add038346/system/CodeIgniter.php#L350-L359

2022-07-11 04:19 UTC, kenjis commented
I think this PR is ready for reviews.
I think this is the best we can do at the moment.

2022-07-11 10:49 UTC, MGatner commented
> `RedirectException` is caught in `CodeIgniter::run()`

Why not make `RedirectException` and `PageNotFoundException` extend `HTTPException` and then catch all `HTTPException` in `run()` and handle them there? These two are currently special cases but I could see a developer wanting to force any HTTP code response at any point via an exception.

2022-07-11 10:53 UTC, MGatner commented
Actually I just read this:

> The exception code has nothing to do with HTTP status code.
> So it is impossible to determine HTTP status code from exception code.

So maybe the exception type is what defines these two special cases and we don't want more robust handling.

2022-07-12 00:33 UTC, kenjis commented
> Why not make RedirectException and PageNotFoundException extend HTTPException and then catch all HTTPException in run() and handle them there?

404 is handled in the exceptionHandler() now.
If we catch all HTTPException in run(), we need to change the current code more.

2022-07-12 01:13 UTC, kenjis commented
I've changed my mind.
This PR changes too much. If we add interfaces or change the parent class, it should go `4.3`.

I sent another PR #6228 with minimum changes for the bug fix.

2022-07-21 14:28 UTC, paulbalandan commented
With the merge of #6254 , is this still needed?

2022-07-22 05:52 UTC, kenjis commented
Yes, #6254 is a workaround.

I think the current behavior is broken. Because Exception code has nothing to do with HTTP status code/Exit code.
If the Exception code means HTTP status code/Exit code, devs should make it explicit.

2022-07-22 23:15 UTC, kenjis commented
It seems to me that it is impossible to use Exception code to represent Exit code. 
If you have already used an Exception code, you cannot specify an Exit code.

I feel it would be better to have `getExitCode()` in `ExitExceptionInterface`.

2022-07-24 01:05 UTC, kenjis commented
I renamed `ExitExceptionInterface` to `hasExitCodeInterface` and added `getExitCode()` method.

2022-07-24 10:49 UTC, MGatner commented on system/Exceptions/hasExitCodeInterface.php
> +interface hasExitCodeInterface
Doesn't this need to be capitalized?

2022-07-24 11:15 UTC, kenjis commented on system/Exceptions/hasExitCodeInterface.php
> +interface hasExitCodeInterface
You are correct!

2022-07-24 11:16 UTC, kenjis commented on system/Exceptions/hasExitCodeInterface.php
> +interface hasExitCodeInterface
Fixed.

2022-07-24 11:27 UTC, MGatner approved these changes
Good by me!

2022-08-04 01:23 UTC, kenjis commented
Added the docs.

2022-08-04 09:46 UTC, MGatner requested changes
Looks good! Some proofing suggestions.

2022-08-04 09:46 UTC, MGatner commented on user_guide_src/source/changelogs/v4.3.0.rst
> +Previously, the CodeIgniter's Exception Handler used the *Exception code* as *HTTP status code* in some cases, and set calculated *Exit code* based on the Exception code. However there is essentially
```suggestion
Previously, CodeIgniter's Exception Handler used the *Exception code* as the *HTTP status code* in some cases, and calculated the *Exit code* based on the Exception code. However there should be no logical connection with Exception code and HTTP Status Code or Exit code.
```

2022-08-04 09:46 UTC, MGatner commented on user_guide_src/source/changelogs/v4.3.0.rst
> +- You can change HTTP status code or Exit code to implements ``HTTPExceptionInterface`` or ``HasExitCodeInterface`` in your Exception class. See :ref:`error-specify-http-status-code` and :ref:`error-
```suggestion
- You can change HTTP status code or Exit code to implement ``HTTPExceptionInterface`` or ``HasExitCodeInterface`` in your Exception class. See :ref:`error-specify-http-status-code` and :ref:`error-specify-exit-code`.
```

2022-08-04 09:46 UTC, MGatner commented on user_guide_src/source/general/errors.rst
> +When an exception implemented ``HTTPExceptionInterface`` is caught by CodeIgniter's exception handler, the Exception code will be the HTTP status code.
```suggestion
When an exception implementing ``HTTPExceptionInterface`` is caught by CodeIgniter's exception handler, the Exception code will become the HTTP status code.
```

2022-08-04 09:46 UTC, MGatner commented on user_guide_src/source/general/errors.rst
> +When an exception implemented ``HasExitCodeInterface`` is caught by CodeIgniter's exception handler, the code returned from the ``getExitCode()`` method will be the exit code.
```suggestion
When an exception implementing ``HasExitCodeInterface`` is caught by CodeIgniter's exception handler, the code returned from the ``getExitCode()`` method will become the exit code.
```

2022-08-04 09:46 UTC, MGatner commented on user_guide_src/source/installation/upgrade_430.rst
> +  In that case, you need to implements ``HTTPExceptionInterface`` in the Exception. See :ref:`error-specify-http-status-code`.
```suggestion
  In that case, you need to implement ``HTTPExceptionInterface`` in the Exception. See :ref:`error-specify-http-status-code`.
```

2022-08-04 09:46 UTC, MGatner commented on user_guide_src/source/installation/upgrade_430.rst
> +  In that case, you need to implements ``HasExitCodeInterface`` in the Exception. See :ref:`error-specify-exit-code`.
```suggestion
  In that case, you need to implement ``HasExitCodeInterface`` in the Exception. See :ref:`error-specify-exit-code`.
```

2022-08-05 10:35 UTC, MGatner approved these changes

2022-08-06 13:27 UTC, merged