docs: improve installation
codeigniter4/CodeIgniter4 pull request #6324
Opened 2022-08-01 02:01 UTC by kenjis

**Description**
- add initial configuration in Installation pages
- add note about baseURL and debug toolbar
- small fixes

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2022-08-01 10:58 UTC, MGatner requested changes
Looks good! A few tweaks.

2022-08-01 10:58 UTC, MGatner commented on user_guide_src/source/installation/installing_composer.rst
> +See :ref:`initial-configuration` for the detail.
```suggestion
After installation, a few initial configurations are required.
See :ref:`initial-configuration` for the details. 
```

2022-08-01 10:58 UTC, MGatner commented on user_guide_src/source/installation/installing_composer.rst
> +See :ref:`initial-configuration` for the detail.
```suggestion
A few initial configurations are required.
See :ref:`initial-configuration` for the details.
```

2022-08-01 10:58 UTC, MGatner commented on user_guide_src/source/installation/installing_manual.rst
> +After installation, a few initial configuration is required.
```suggestion
After installation, a few initial configurations are required.
```

2022-08-02 07:02 UTC, kenjis commented
@MGatner Thank you for proofreading!

2022-08-02 11:13 UTC, MGatner commented
Anytime! I know I've said it before: your English is incredibly strong for a non-native speaker! 

Most of these corrections aren't actual problems so much as native phrasing, so if you ever get tired of my nitpicks then just tell me to stop 😅

2022-08-02 11:13 UTC, MGatner approved these changes

2022-08-02 23:03 UTC, merged

2022-08-02 23:06 UTC, kenjis commented
No problem. Proofreading is welcome!
In fact we have only two active proofreaders now, you and Paul.