Fix validation custom error asterisk field
codeigniter4/CodeIgniter4 pull request #6378
Opened 2022-08-15 08:43 UTC by ping-yee

**Description**
Fixes #6245 
Supersedes #6352 

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2022-08-16 02:49 UTC, kenjis commented on user_guide_src/source/changelogs/v4.2.5.rst
> +- The method signature of ``Validation.php::processRules()`` and ``Validation.php::getErrorMessage()`` have been changed. Both of these methods add new ``$originalField`` parameter.
```suggestion
- The method signature of ``Validation::processRules()`` and ``Validation::getErrorMessage()`` have been changed. Both of these methods add new ``$originalField`` parameter.
```

2022-08-16 18:32 UTC, ping-yee commented on user_guide_src/source/changelogs/v4.2.5.rst
> +- The method signature of ``Validation.php::processRules()`` and ``Validation.php::getErrorMessage()`` have been changed. Both of these methods add new ``$originalField`` parameter.
I have been changed!

2022-08-18 11:45 UTC, ping-yee commented
May I `rebase` to solve resolve conflicts?

2022-08-18 12:21 UTC, kenjis commented
> May I rebase to solve resolve conflicts?

Yes, please.

2022-08-18 21:26 UTC, kenjis commented
Thanks, but it is not "rebase", because you added another commit. 
How did you do?

See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch

2022-08-19 17:37 UTC, ping-yee commented
@kenjis I reset my git flow and re-rebase, is there the git flow show normally this time?
After I finish re-rebase, I added the test for validation.

2022-08-22 02:38 UTC, kenjis approved these changes

2022-08-22 02:40 UTC, kenjis commented
Thank you. It looks good.
If all GitHub Action checks pass, I will merge this.

2022-08-22 03:04 UTC, kenjis commented
@ping-yee Please fix coding style.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style

```diff
   1) CodeIgniter4/tests/system/Validation/ValidationTest.php (trailing_comma_in_multiline, unary_operator_spaces, not_operator_with_successor_space)
      ---------- begin diff ----------
--- /home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Validation/ValidationTest.php
+++ /home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Validation/ValidationTest.php
@@ -472,7 +472,7 @@
             'foo' => [
                 ['bar' => null],
                 ['bar' => null],
-            ]
+            ],
         ];
         $this->validation->setRules(
             ['foo.*.bar' => ['label' => 'foo bar', 'rules' => 'required']],
@@ -481,7 +481,7 @@
         $this->validation->run($data);
         $this->assertSame([
             'foo.0.bar' => 'Required',
-            'foo.1.bar' => 'Required'
+            'foo.1.bar' => 'Required',
         ], $this->validation->getErrors());
     }
 

      ----------- end diff -----------
```

2022-08-22 03:04 UTC, kenjis requested changes
Please fix coding style.

2022-08-22 16:02 UTC, ping-yee commented
@kenjis I have been fix my coding style.
Thank for your continuous helping, I’m very grateful.

2022-08-22 21:46 UTC, merged

2022-08-22 21:46 UTC, kenjis commented
@ping-yee Thank you!