docs: update about test database setup
codeigniter4/CodeIgniter4 pull request #6416
Opened 2022-08-23 09:07 UTC by kenjis

**Description**
There seems no reason to use `phpunit.xml`.

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [] Conforms to style guide

2022-08-23 10:47 UTC, MGatner requested changes
I would like to keep the mention of **phpunit.xml** - that is my preferred method (swapping between the **.dist** version).

2022-08-23 11:30 UTC, kenjis commented
Done!

2022-08-23 13:26 UTC, paulbalandan commented on tests/README.md
> +The default configuration uses SQLite3 memory database, so it works if you can use SQLite3.
```suggestion
The default configuration uses SQLite3 transient in-memory database, so it works if you can use SQLite3.
```

2022-08-24 03:08 UTC, paulbalandan approved these changes

2022-08-24 10:58 UTC, MGatner approved these changes
Thanks @kenjis ❤️ Don't want to get on Sebastian Bergmann's bad side 🫣

2022-08-25 00:46 UTC, merged