- FIX: in command prompt
codeigniter4/CodeIgniter4 pull request #6452
Opened 2022-08-29 15:27 UTC by daycry

at SYSTEMPATH\Validation\FileRules.php:42

Backtrace:
  1    [internal function]
       CodeIgniter\Debug\Exceptions()->errorHandler(2, 'assert(): assert($request instanceof IncomingRequest) failed', 'C:\\laragon\\www\\test\\vendor\\codeigniter4\\framework\\system\\Validation\\FileRules.php', 42, [...])

Each pull request should address a single issue and have a meaningful title.

- All bug fixes should be sent to the __"develop"__ branch, this is where the next bug fix version will be developed.
- PRs with any enhancement should be sent to the next minor version branch, e.g. __"4.3"__

**Description**
Explain what you have changed, and why.

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

2022-08-29 18:53 UTC, Mauricevb commented
I aso ran into this issue when executing `php spark db:seed <seeder>` from the terminal. Thank you for the PR! 


<details>
  <summary>Backtrace</summary>
  
```
[AssertionError]

assert($request instanceof IncomingRequest)

at SYSTEMPATH/Validation/FileRules.php:42

Backtrace:
  1    SYSTEMPATH/Validation/FileRules.php:42
       assert(false, 'assert($request instanceof IncomingRequest)')

  2    SYSTEMPATH/Validation/Validation.php:558
       CodeIgniter\Validation\FileRules()->__construct()

  3    SYSTEMPATH/Validation/Validation.php:122
       CodeIgniter\Validation\Validation()->loadRuleSets()

  4    SYSTEMPATH/CLI/CLI.php:324
       CodeIgniter\Validation\Validation()->run([...])

  5    SYSTEMPATH/CLI/CLI.php:257
       CodeIgniter\CLI\CLI::validate('temp', 'n', [...])

  6    APPPATH/Database/Seeds/MySeeder.php:22
       .....
  ```
</details>

2022-08-29 19:12 UTC, daycry commented
I created a pull request for solve this issue.

Thank you!

2022-08-29 19:33 UTC, daycry commented
Do I need anything for merge this pull un develop branch?

2022-08-29 22:52 UTC, iRedds commented
@Mauricevb What version are you using?
4.2.5 can not reproduce.

2022-08-29 22:56 UTC, iRedds commented
@daycry You need a normal description of the problem and tests, because it is not clear what behavior your PR corrects.

2022-08-29 22:57 UTC, kenjis commented
@daycry Thank you for trying to improve CI4!

You need to:
- pass all GitHub Action checks
  - there is a PHPStan error: https://github.com/codeigniter4/CodeIgniter4/runs/8074111212?check_suite_focus=true
- write test code to prove the bug is fixed
  - see https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

2022-08-30 02:56 UTC, ddevsr requested changes
If you use validation for CLI, now can use IncomingRequest only.

You must set `assert($request instanceof CLIRequest ?? IncomingRequest)`, and now can use for CLI and Web

2022-08-30 07:23 UTC, paulbalandan commented on system/Validation/FileRules.php
> +        assert($request instanceof CLIRequest ?? IncomingRequest)
This is not nullable, how would this work?

2022-08-30 07:24 UTC, daycry commented
You can reproduce the error with this code for example

CLI::prompt('Config file already exists, do you want to replace it?', [ 'y', 'n' ]) == 'n')

When you try to validate a input with cli commands, you can see the error.

2022-08-30 08:01 UTC, kenjis commented
```php
CLI::prompt('Config file already exists, do you want to replace it?', [ 'y', 'n' ]) == 'n')
```

I got:
```
[ParseError]

Unclosed '{' on line 10 does not match ')'
```

2022-08-30 08:26 UTC, kenjis commented
I was able to reproduce.

```php
<?php

namespace App\Controllers;

use CodeIgniter\CLI\CLI;

class Home extends BaseController
{
    public function index()
    {
        $email = CLI::prompt('What is your email?', null, 'required|valid_email');
    }
}
```
```console
$ php public/index.php 
What is your email? : 


[AssertionError]

assert($request instanceof IncomingRequest)

at SYSTEMPATH/Validation/FileRules.php:42
```

2022-08-30 08:33 UTC, kenjis commented
`Validation::loadRuleSets()` creates all validation rule instances when `Validation::run()` is called.

https://github.com/codeigniter4/CodeIgniter4/blob/f1862a0217851364407407e3d0193d80d2fc69e5/system/Validation/Validation.php#L551-L560

2022-08-30 08:50 UTC, daycry commented
I use this code for copy Config file in Config namespace.

if (file_exists($appPath . $path) && CLI::prompt('Config file already exists, do you want to replace it?', [ 'y', 'n' ]) == 'n') {
            CLI::error('Cancelled');
            exit();
        }
.

[ErrorException]

assert(): assert($request instanceof IncomingRequest) failed

at SYSTEMPATH\Validation\FileRules.php:42

Backtrace:
  1    [internal function]
       CodeIgniter\Debug\Exceptions()->errorHandler(2, 'assert(): assert($request instanceof IncomingRequest) failed', 'C:\\laragon\\www\\test\\vendor\\codeigniter4\\framework\\system\\Validation\\FileRules.php', 42, [...])
This code return this error


My first PR solve this error, because $request are CliRequest no IncomingRequest class

assert($request instanceof IncomingRequest); -->assert($request instanceof Request);

Because extends from Request, but phpstan check return error.

Later, I try this change 

assert($request instanceof IncomingRequest || $request instanceof CLIRequest)

but docker postgre return and error, I think that this error isn't from the code, later will tray again.

Thank you!

2022-08-30 08:55 UTC, ddevsr commented
> `Validation::loadRuleSets()` creates all validation rule instances when `Validation::run()` is called.
> 
> https://github.com/codeigniter4/CodeIgniter4/blob/f1862a0217851364407407e3d0193d80d2fc69e5/system/Validation/Validation.php#L551-L560

@kenjis In prompt CLI by default running validate if parameter `$validation` not `null`
https://github.com/codeigniter4/CodeIgniter4/blob/f1862a0217851364407407e3d0193d80d2fc69e5/system/CLI/CLI.php#L257

https://github.com/codeigniter4/CodeIgniter4/blob/f1862a0217851364407407e3d0193d80d2fc69e5/system/CLI/CLI.php#L313-L333

2022-08-30 09:05 UTC, ddevsr commented
I already test this PR, fix validation in CLI.

![image](https://user-images.githubusercontent.com/97607754/187396506-6216d0b1-ba42-4c80-b520-b559465f0e9d.png)

2022-08-30 09:14 UTC, kenjis commented
> I already test this PR, fix validation in CLI.

Yes, this works.
```console
$ php public/index.php 
What is your email? : 
The What is your email? field is required.
What is your email? : 
```

2022-08-30 09:14 UTC, kenjis approved these changes

2022-08-30 10:40 UTC, merged

2022-08-30 11:42 UTC, kenjis commented
The Validation `FileRules` only works with Uploaded Files (HTTP). So in CLI it does not work.
Therefore the request object in it should be `IncommingRequest`.

But `Validation::run()` instantiate all the rule object, so `FileRules` is also instantiated even if in CLI.
And it causes AssertionError.

This PR is workaround.

2022-09-01 02:47 UTC, kenjis commented
This issue is more serious than what I thought first.

```console
$ php spark shield:setup

CodeIgniter v4.2.5 Command Line Tool - Server Time: 2022-09-01 11:41:17 UTC+09:00

  Created: APPPATH/Config/Auth.php
  Created: APPPATH/Config/AuthGroups.php
  Updated: APPPATH/Controllers/BaseController.php
  Updated: APPPATH/Config/Routes.php
  Updated: We have updated file 'APPPATH/Config/Security.php' for security reasons.
  Run `spark migrate --all` now? [y, n]: y

[AssertionError]

assert($request instanceof IncomingRequest)

at SYSTEMPATH/Validation/FileRules.php:42

Backtrace:
  1    SYSTEMPATH/Validation/FileRules.php:42
       assert(false, 'assert($request instanceof IncomingRequest)')

  2    SYSTEMPATH/Validation/Validation.php:558
       CodeIgniter\Validation\FileRules()->__construct()

  3    SYSTEMPATH/Validation/Validation.php:122
       CodeIgniter\Validation\Validation()->loadRuleSets()

  4    SYSTEMPATH/CLI/CLI.php:324
       CodeIgniter\Validation\Validation()->run([...])

  5    SYSTEMPATH/CLI/CLI.php:257
       CodeIgniter\CLI\CLI::validate('temp', 'y', [...])

  6    VENDORPATH/codeigniter4/shield/src/Commands/Setup.php:316
       CodeIgniter\CLI\CLI::prompt('  Run `spark migrate --all` now?', [...])

  7    VENDORPATH/codeigniter4/shield/src/Commands/Setup.php:302
       CodeIgniter\Shield\Commands\Setup()->cliPrompt('  Run `spark migrate --all` now?', [...])

  8    VENDORPATH/codeigniter4/shield/src/Commands/Setup.php:92
       CodeIgniter\Shield\Commands\Setup()->runMigrations()

  9    VENDORPATH/codeigniter4/shield/src/Commands/Setup.php:79
       CodeIgniter\Shield\Commands\Setup()->publishConfig()

 10    SYSTEMPATH/CLI/Commands.php:63
       CodeIgniter\Shield\Commands\Setup()->run([])

 11    SYSTEMPATH/CLI/CommandRunner.php:65
       CodeIgniter\CLI\Commands()->run('shield:setup', [])

 12    SYSTEMPATH/CLI/CommandRunner.php:51
       CodeIgniter\CLI\CommandRunner()->index([])

 13    SYSTEMPATH/CodeIgniter.php:897
       CodeIgniter\CLI\CommandRunner()->_remap('index', [...])

 14    SYSTEMPATH/CodeIgniter.php:457
       CodeIgniter\CodeIgniter()->runController(Object(CodeIgniter\CLI\CommandRunner))

 15    SYSTEMPATH/CodeIgniter.php:336
       CodeIgniter\CodeIgniter()->handleRequest(null, Object(Config\Cache), false)

 16    SYSTEMPATH/CLI/Console.php:48
       CodeIgniter\CodeIgniter()->run()

 17    ROOTPATH/spark:98
       CodeIgniter\CLI\Console()->run()
```

2022-09-01 06:42 UTC, jozefrebjak commented
> This issue is more serious than what I thought first.
> 
> ```
> $ php spark shield:setup
> 
> CodeIgniter v4.2.5 Command Line Tool - Server Time: 2022-09-01 11:41:17 UTC+09:00
> 
>   Created: APPPATH/Config/Auth.php
>   Created: APPPATH/Config/AuthGroups.php
>   Updated: APPPATH/Controllers/BaseController.php
>   Updated: APPPATH/Config/Routes.php
>   Updated: We have updated file 'APPPATH/Config/Security.php' for security reasons.
>   Run `spark migrate --all` now? [y, n]: y
> 
> [AssertionError]
> 
> assert($request instanceof IncomingRequest)
> 
> at SYSTEMPATH/Validation/FileRules.php:42
> 
> Backtrace:
>   1    SYSTEMPATH/Validation/FileRules.php:42
>        assert(false, 'assert($request instanceof IncomingRequest)')
> 
>   2    SYSTEMPATH/Validation/Validation.php:558
>        CodeIgniter\Validation\FileRules()->__construct()
> 
>   3    SYSTEMPATH/Validation/Validation.php:122
>        CodeIgniter\Validation\Validation()->loadRuleSets()
> 
>   4    SYSTEMPATH/CLI/CLI.php:324
>        CodeIgniter\Validation\Validation()->run([...])
> 
>   5    SYSTEMPATH/CLI/CLI.php:257
>        CodeIgniter\CLI\CLI::validate('temp', 'y', [...])
> 
>   6    VENDORPATH/codeigniter4/shield/src/Commands/Setup.php:316
>        CodeIgniter\CLI\CLI::prompt('  Run `spark migrate --all` now?', [...])
> 
>   7    VENDORPATH/codeigniter4/shield/src/Commands/Setup.php:302
>        CodeIgniter\Shield\Commands\Setup()->cliPrompt('  Run `spark migrate --all` now?', [...])
> 
>   8    VENDORPATH/codeigniter4/shield/src/Commands/Setup.php:92
>        CodeIgniter\Shield\Commands\Setup()->runMigrations()
> 
>   9    VENDORPATH/codeigniter4/shield/src/Commands/Setup.php:79
>        CodeIgniter\Shield\Commands\Setup()->publishConfig()
> 
>  10    SYSTEMPATH/CLI/Commands.php:63
>        CodeIgniter\Shield\Commands\Setup()->run([])
> 
>  11    SYSTEMPATH/CLI/CommandRunner.php:65
>        CodeIgniter\CLI\Commands()->run('shield:setup', [])
> 
>  12    SYSTEMPATH/CLI/CommandRunner.php:51
>        CodeIgniter\CLI\CommandRunner()->index([])
> 
>  13    SYSTEMPATH/CodeIgniter.php:897
>        CodeIgniter\CLI\CommandRunner()->_remap('index', [...])
> 
>  14    SYSTEMPATH/CodeIgniter.php:457
>        CodeIgniter\CodeIgniter()->runController(Object(CodeIgniter\CLI\CommandRunner))
> 
>  15    SYSTEMPATH/CodeIgniter.php:336
>        CodeIgniter\CodeIgniter()->handleRequest(null, Object(Config\Cache), false)
> 
>  16    SYSTEMPATH/CLI/Console.php:48
>        CodeIgniter\CodeIgniter()->run()
> 
>  17    ROOTPATH/spark:98
>        CodeIgniter\CLI\Console()->run()
> ```

I had the same problem today with fresh v4.2.4 and `shield:setup` command.

2022-09-01 07:47 UTC, datamweb commented
@kenjis and @jozefrebjak I cannot reproduce if:
CI 4.2.5 (whit applay this PR) and shield (last dev)

![Screenshot 2022-09-01 111046](https://user-images.githubusercontent.com/9530214/187860057-b994b74b-5efb-4d11-8653-017cfe5e861b.jpg)

2022-09-01 07:56 UTC, kenjis commented
@datamweb Yes, this PR fixes the error.

2022-09-01 10:32 UTC, MGatner commented
Should we hotfix this @kenjis ?

2022-09-01 11:12 UTC, kenjis commented
@MGatner If possible, v4.2.6 should be released as soon as possible.

Now the commands that use `CLI::prompt()` with the validation do not work at all.

2022-09-02 09:33 UTC, MGatner commented
Did this happen because we are lacking tests? Or is it because CLI and requests are hard to test under "real" scenarios? Or...?

2022-09-02 12:42 UTC, kenjis commented
Both.
First, `CLI::prompt()` is untestable in 4.2.x.
We don't have  integration test for a CLI commnad with `CLI::prompt()` in 4.3.