fix: [Validation] JSON data may cause "Array to string conversion" error
codeigniter4/CodeIgniter4 pull request #6467
Opened 2022-09-01 09:03 UTC by kenjis

**Description**
Fixes #6466

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2022-09-01 11:09 UTC, MGatner requested changes

2022-09-02 03:40 UTC, kenjis commented on system/Validation/Validation.php
> +            if (! is_int($key)) {
Done.

2022-09-02 03:48 UTC, kenjis commented
Rebased and squashed.
Added a check if the array is a list (in the meaning of `array_is_list()`).

2022-09-02 10:03 UTC, MGatner approved these changes

2022-09-02 22:05 UTC, merged