fix: required_with does not work in Model updates with Entity
codeigniter4/CodeIgniter4 pull request #6588
Opened 2022-09-26 07:10 UTC by kenjis

**Description**
Fixes #6577

1. Validation in `insert()`/`insertBatch()` always uses entire rules (force to set `$this->cleanValidationRules = false`).
2. Validation in `update()`/`updateBatch()`/`replace()` uses `$this->cleanValidationRules` value.
3. You can change `$this->cleanValidationRules` value with `cleanRules()`.
4. If `$this->cleanValidationRules = false`, get all data (`$onlyChanged = false`) from the Entity.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2022-09-29 03:04 UTC, kenjis commented
Added the docs.

2022-09-29 11:12 UTC, MGatner commented
This is bigger than I can do right now, but I will come back to it. It looks good, but the situation is difficult to understand. 

I have mentioned this a few times, but I think our validation has grown over-complicated because it is trying to do too much.

2022-09-29 11:27 UTC, kenjis commented
Yes, this is not small.
However, I believe this fix is the implementation it should have been originally; 
the `cleanValidationRules` property was provided for that purpose. I can only assume that it is.

2022-09-30 10:00 UTC, MGatner requested changes
Made some comments, but just to make sure I have my head around to this correctly... Right now, if I have a model:
```php
            protected $validationRules = [
    'name' => 'required',
]
```
This will work:
```php
$model->cleanRules(true)->insert(['color' => 'brown']);
```

2022-09-30 10:17 UTC, kenjis commented
```php
// Model
protected $validationRules = [
    'name' => 'required',
]

// Controller
$model->cleanRules(true)->insert(['color' => 'brown']);
```

This does not work, both in before this PR and after this PR.
Before: `insert()` calls `$this->cleanRules()` inside.
After: `insert()` sets `$this->cleanValidationRules = false` inside.

2022-09-30 10:34 UTC, kenjis commented on tests/system/Models/ValidationModelTest.php
> +            'field2' => '',
Yes, you're correct! Fixed.

2022-09-30 10:43 UTC, kenjis commented on tests/system/Models/ValidationModelTest.php
> +    public function testUpdateEntityWithCleanValidationRulesFalse()
It is indeed almost the same, but testing two patterns.

1. `$cleanValidationRules = true` and `cleanRules()`
2. `$cleanValidationRules = false`

2022-10-01 09:58 UTC, MGatner commented
> Before: `insert()` calls `$this->cleanRules()` inside.

Right, so in my example the rule for `name` gets cleaned so the insert would succeed. 

If I've understood this correctly it could be a breaking change with some impactful side effects.

2022-10-01 10:04 UTC, MGatner commented on tests/system/Models/ValidationModelTest.php
> +    public function testUpdateEntityWithCleanValidationRulesFalse()
But my point was: really all you're testing is that `cleanRules()` sets the `cleanValidationRules` property, so why not either test that or just skip the duplication?

2022-10-01 10:49 UTC, kenjis commented
This seems bad default value, but `cleanRules()` equals `cleanRules(false)`:
https://github.com/codeigniter4/CodeIgniter4/blob/ed0cdd00eaf20f7d6efb373af991111ead4fece8/system/BaseModel.php#L1314

2022-10-01 11:02 UTC, kenjis commented on tests/system/Models/ValidationModelTest.php
> +    public function testUpdateEntityWithCleanValidationRulesFalse()
My point is:
1. Model with $cleanValidationRules = true
2. Model with $cleanValidationRules = false

How do we remove the duplication?

2022-10-02 10:58 UTC, MGatner commented
Ohhh gotcha! Yeah that was the piece I was missing! Thanks for explaining. I'm good with this then.

2022-10-02 10:58 UTC, MGatner approved these changes

2022-10-03 00:27 UTC, merged