docs: improve session
codeigniter4/CodeIgniter4 pull request #6593
Opened 2022-09-27 00:27 UTC by kenjis

**Description**
Small improvements or fixes.

If we agree, I would like to remve all sample code that uses `$_SESSION` directly.

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [] Conforms to style guide

2022-09-28 10:06 UTC, MGatner requested changes
I think the UG used "userdata" throughout to indicate "non-flash data stored by the framework", because some actual `$_SESSION` items are not included:
```php
$_exclude = array_merge(['__ci_vars'], $this->getFlashKeys(), $this->getTempKeys());
```
I'm fine with making this a little more opaque but we should note somewhere what is _not_ included. 

Otherwise: I am in favor of encouraging use of the Session handler over the global variable.

2022-09-28 10:23 UTC, kenjis commented on user_guide_src/source/libraries/sessions.rst
> +CodeIgniter 3 has a completely re-written Session library.
No, this is historical explanation.
Ci 2.x Session did not have locking, then to solve the issues, CI3 had a completely re-written Session library.

CI4 may have a completely re-written Session library, but lack of locking is not the main reason.

2022-09-29 02:15 UTC, kenjis commented
There are some notes (important) to describe the items that the `get()` method returns
like the following:
> The get() method WILL return flashdata or tempdata items when retrieving a single item by key. It will not return flashdata or tempdata when grabbing all data from the session, however.

And I added a note for the word "userdata".

2022-09-29 08:22 UTC, datamweb approved these changes

2022-09-29 10:45 UTC, MGatner approved these changes
Sorry, I missed those other comments. Thank you for updating. LGTM!

2022-09-29 10:50 UTC, merged