test: fix ResponseTest::testSetDateRemembersDateInUTC
codeigniter4/CodeIgniter4 pull request #6632
Opened 2022-10-06 00:15 UTC by kenjis

**Description**
Fixes #5486

- fix tests that depends on time

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

2022-10-06 10:21 UTC, MGatner requested changes
Don't forget the new modifiers!

~~Also: what is the point of this? Clone and replace a brand new object?~~

Never mind! I see now, the `setDate()` call is before the clone.

2022-10-06 11:18 UTC, kenjis commented on tests/system/HTTP/DownloadResponseTest.php
> +        $datetime = DateTime::createFromFormat('Y-m-d', '2000-03-10');
@paulbalandan Why doesn't php-cs-fixer add `!` ?

2022-10-06 11:42 UTC, paulbalandan commented on tests/system/HTTP/DownloadResponseTest.php
> +        $datetime = DateTime::createFromFormat('Y-m-d', '2000-03-10');
I tested and seems to be a bug.

2022-10-07 10:46 UTC, MGatner approved these changes

2022-10-07 11:37 UTC, merged