Bug: DateHelperTest::testNowSpecific depends on time
codeigniter4/CodeIgniter4 pull request #6684
Opened 2022-10-14 11:10 UTC by fpoy

Fixes #5492

**Description**

In the `testNowSpecific()` method, there are two different `now()` calls

There may be sometimes a latency between the two calls, and by default `assertCloseEnough` test if the difference is lower than 1 second.

To reproduce, just add a delay `sleep(n)` inside the `now()` function

A solution may be to increase the tolerance threshold to an acceptable level (eg 10 sec for 2 hours should be sufficient)

**Checklist:**

- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2022-10-14 11:22 UTC, kenjis commented
The true solution is to stop time during testing.
But for the time being this PR may be okay.

To be hoest, I would like to deprecate the `now()` function,
or at least to deprecate the parameter `$timezone`.
Because I don't understand Unix timestamp with timezone.

2022-10-14 21:33 UTC, kenjis commented on tests/system/Helpers/DateHelperTest.php
> +        $this->assertCloseEnough(7200, now('America/Chicago') - now('America/Vancouver'), '', 10);
After all, this test is strange.
It is difficult to accept the *specification* that a 10-second error is not a problem.

2022-10-14 21:35 UTC, kenjis requested changes
Sorry, I don't accept this.
Because test code is a specification.

2022-10-15 10:42 UTC, MGatner commented
Is the test actually failing? 1 second should be ample time to cover any single test case (especially that doesn't involve database or HTTP).

2022-10-25 01:11 UTC, kenjis commented
```
1) CodeIgniter\Helpers\DateHelperTest::testNowSpecific
Failed asserting that 4 is equal to 1 or is less than 1.

/home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/CIUnitTestCase.php:478
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Helpers/DateHelperTest.php:36
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:97
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/3317017866/jobs/5479434095

2022-10-25 05:25 UTC, kenjis commented
I sent another PR #6753

2022-11-05 23:56 UTC, kenjis commented
Closed by #6753

2022-11-05 23:56 UTC, closed without merging