docs: add how to add X-Requested-With header with htmx
codeigniter4/CodeIgniter4 pull request #6720
Opened 2022-10-19 22:44 UTC by kenjis

**Description**
- add how to add X-Requested-With header with htmx

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2022-10-20 07:13 UTC, datamweb requested changes

2022-10-20 07:13 UTC, datamweb commented on user_guide_src/source/general/ajax.rst
> +=====
```suggestion
====
```

2022-10-20 07:21 UTC, kenjis commented on user_guide_src/source/general/ajax.rst
> +=====
Oh, thanks!

2022-10-20 10:57 UTC, MGatner approved these changes
Good by me! Maybe give @lonnieezell a day then go for it - we can always pull it later.

2022-10-20 13:16 UTC, lonnieezell approved these changes
I like this addition. We already have the other big ones, and I'd love to push htmx more, honestly.

2022-10-20 17:38 UTC, michalsn approved these changes

2022-10-20 20:28 UTC, merged

2022-10-23 18:44 UTC, jozefrebjak commented
@kenjis Nice!