refactor: replace `time()` with Time into `Debug` and `Cookie` class.
codeigniter4/CodeIgniter4 pull request #6860
Opened 2022-11-14 08:34 UTC by ping-yee

**Description**
See #6815 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2022-11-14 11:32 UTC, MGatner approved these changes
Looks good! Nice micro-timing 🤗

2022-11-14 18:00 UTC, michalsn requested changes

2022-11-15 11:11 UTC, MGatner commented on system/Debug/Toolbar.php
> +            $time = sprintf('%.6f', Time::now()->format('u'));
Oh! Good catch. Yeah I screwed that up 🤦‍♂️

2022-11-15 18:04 UTC, michalsn approved these changes
Thanks.

2022-11-15 23:18 UTC, kenjis approved these changes

2022-11-15 23:18 UTC, merged