new make:cell command
codeigniter4/CodeIgniter4 pull request #6864
Opened 2022-11-15 04:36 UTC by lonnieezell

Provides a new `make:cell` command to generate a controlled cell and its accompanying view. 

This includes a refactor on the GeneratorTrait to split out file creation to `generateClass` and `generateView`. The first working much like the existing `execute()` method which has been refactored to use the `generateClass` method.

2022-11-15 07:08 UTC, paulbalandan commented on tests/system/Commands/CellGeneratorTest.php
> + * @internal
```suggestion
 * @internal
 *
 * @group Others
```

2022-11-17 03:50 UTC, ddevsr requested changes
`$file` is unused, can remove or using it

2022-11-17 03:50 UTC, ddevsr commented on tests/system/Commands/CellGeneratorTest.php
> +        $this->assertFileExists(APPPATH . 'Cells/recent_cell.php');
```suggestion
        $this->assertFileExists($file);
```

2022-11-17 03:50 UTC, ddevsr commented on tests/system/Commands/CellGeneratorTest.php
> +        $this->assertFileExists(APPPATH . 'Cells/another_cell.php');
```suggestion
        $this->assertFileExists($file);
```

2022-11-17 04:09 UTC, kenjis commented on tests/system/Commands/CellGeneratorTest.php
> +     */
`@group` for methods is not needed.

2022-11-17 04:09 UTC, kenjis commented on tests/system/Commands/CellGeneratorTest.php
> +     */
`@group` for methods is not needed.

2022-11-17 04:11 UTC, kenjis commented on tests/system/Commands/CellGeneratorTest.php
> +    private function cleanUp()
Please remove unused method. See rector error.

2022-11-17 04:20 UTC, lonnieezell commented on tests/system/Commands/CellGeneratorTest.php
> +    private function cleanUp()
Done

2022-11-17 04:20 UTC, lonnieezell commented on tests/system/Commands/CellGeneratorTest.php
> +     */
Removed

2022-11-17 04:20 UTC, lonnieezell commented on tests/system/Commands/CellGeneratorTest.php
> +     */
Removed

2022-11-17 04:53 UTC, merged