docs: update DB transactions
codeigniter4/CodeIgniter4 pull request #6886
Opened 2022-11-20 05:35 UTC by kenjis

**Description**
- update docs
- add tests

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

2022-11-22 00:28 UTC, sclubricants commented
How about a test with `$this->db->transStrict(false);`  This would change these test outcomes right?

2022-11-22 01:26 UTC, kenjis commented
I don't know why Strict Mode is needed.

2022-11-22 01:45 UTC, kenjis commented
> How about a test with $this->db->transStrict(false); This would change these test outcomes right?

Added. It works as expected.

But it seems the strict mode makes sense only when DBDebug is false.
Since v4.3.0, DBDebug is true by default, so if one query fails, an exception will be thrown and that's all.

Is the strict mode a safeguard that prevents all subsequent transactions from being executed if one transaction fails when there were no exceptions?

2022-11-22 18:52 UTC, sclubricants commented
Adding the transaction status helps to understand the tests better.

>But it seems the strict mode makes sense only when DBDebug is false.

yes, then you can use `$this->db->transStatus()` to determine what to do.

I wonder if calling `$this->db->transCommit();` or `$this->db->transRollback()`  will then allow you to start new transactions again or if they will keep failing.

2022-11-22 19:41 UTC, sclubricants commented
There is no resetTrans() method. In case you wanted to try a series of transactions again while in strict mode.. 

It can be accomplished like this however:

```php
    public function resetTransAfterFailure()
    {
        $this->disableDBDebug();

        $builder = $this->db->table('job');

        $this->db->transStrict(true);

        // The first transaction group
        $this->db->transStart();

        $jobData = [
            'name'        => 'Grocery Sales',
            'description' => 'Discount!',
        ];
        $builder->insert($jobData);

        $this->assertTrue($this->db->transStatus());

        // Duplicate entry '1' for key 'PRIMARY'
        $jobData = [
            'id'          => 1,
            'name'        => 'Comedian',
            'description' => 'Theres something in your teeth',
        ];
        $builder->insert($jobData);

        $this->assertFalse($this->db->transStatus());

        $this->db->transComplete();

        $this->dontSeeInDatabase('job', ['name' => 'Grocery Sales']);


        $this->db->transStrict(false); // resets transaction status
        $this->db->transComplete(); // resets transaction status
        $this->db->transStrict(true); // return back to strick mode


        // The second transaction group
        $this->db->transStart();

        $jobData = [
            'name'        => 'Comedian',
            'description' => 'Theres something in your teeth',
        ];
        $builder->insert($jobData);

        $this->assertTrue($this->db->transStatus());

        $this->db->transComplete();

        $this->seeInDatabase('job', ['name' => 'Comedian']);

        $this->enableDBDebug();
    }
```

2022-11-22 19:53 UTC, sclubricants commented
>But it seems the strict mode makes sense only when DBDebug is false.

We should show how to turn debug off in the managing errors section. 
https://codeigniter4.github.io/CodeIgniter4/database/transactions.html#managing-errors

2022-11-22 19:57 UTC, sclubricants requested changes

2022-11-22 20:07 UTC, sclubricants commented
Can you add this method and documentation?

```php
    /**
     * Reset transaction status - to restart transactions after strict mode failure
     */
    public function resetTransStatus(): BaseConnection
    {
        $this->transStatus = true;

        return $this;
    }
```

2022-11-22 20:27 UTC, sclubricants commented
We probably need a public method on BaseConnection to set debug mode.

2022-11-23 07:43 UTC, kenjis commented
> We probably need a public method on BaseConnection to set debug mode.

Do you need `DBDebug = false`?
Since v4.3.0, `DBDebug` is true by default in all environments,
and I would like to deprecate `DBDebug` in the future.

Since PHP 8.0, PDO throws exceptions by default:
https://www.php.net/manual/en/pdo.error-handling.php

2022-11-23 08:30 UTC, kenjis commented
> We should show how to turn debug off in the managing errors section.
https://codeigniter4.github.io/CodeIgniter4/database/transactions.html#managing-errors

I added a comment in the sample code.

2022-11-23 12:53 UTC, MGatner requested changes
A few typos, otherwise looks good!

2022-11-23 12:53 UTC, MGatner commented on user_guide_src/source/database/transactions.rst
> +    When ``DBDebug`` is true, if an query error occurs, all the queries
```suggestion
    When ``DBDebug`` is true, if a query error occurs, all the queries
```

2022-11-23 12:53 UTC, MGatner commented on user_guide_src/source/database/transactions.rst
> +    When ``DBDebug`` is true, if an query error occurs, all the queries
```suggestion
    When ``DBDebug`` is true, if a query error occurs, all the queries
```

2022-11-23 12:53 UTC, MGatner commented on user_guide_src/source/database/transactions.rst
> +    When ``DBDebug`` is true, if an query error occurs, all the queries
```suggestion
    When ``DBDebug`` is true, if a query error occurs, all the queries
```

2022-11-23 17:47 UTC, sclubricants commented
>I added a comment in the sample code.

I really wish we had a method. ` $this->db->setDBDebug(false);` You can't depend on the database config for handling these. Maybe you have it turned off in one environments and on in another. It kind of defeats the purpose of having `transStatus()` if it always throws an error. 

Perhaps a better way to handle this would be to have a parameter on `transStart()` or a separate method `transError(true/false)`. 

I looked back in my own code where I used transactions and found that I had implemented a workflow using `transStatus()`  but I had a comment by ```$this->db->transComplete(); // throws error?```. 

We need an easy way to set the failure behavior other than the database config file.

2022-11-23 23:41 UTC, kenjis commented
@codeigniter4/database-team 

Before v4.3.0, `DBDebug` was `false` in production environment, but `true` in other environments.
It is very bad practice, because many devs don't know the behavior will change only in production environment.
In develop environment, CI throws an exception but not in production environment.

Since v4.3.0, `DBDebug` is always `true` by default, and it has become nothing to do with debugging (showing errors). 
It is just a flag to throw an exception or not. It is error mode.

> It kind of defeats the purpose of having `transStatus()` if it always throws an error.

Yes, now in `4.3`, `transStatus()` does not work at all unless you set `DBDebug = false`.
By default if a query error occurs, it will be automatically rolled back and an exception will be thrown.

`DBDebug` is error mode in 4.3, and there seems to be no need to change it at runtime. 
So I would like to remove the setting if possible. I don't want to add a new method to change it.

> Perhaps a better way to handle this would be to have a parameter on `transStart()` or a separate method `transError(true/false)`.

I feel that such a way is necessary unless we remove manual transactions functionality.
It seems removing manual transactions is difficult.

2022-11-24 11:23 UTC, MGatner commented
I was strongly in favor of the DBDebug changes and @kenjis' explanation seems like the next logical steps. I've never actually used our `trans____()` methods so don't have a suggestion on how what the best implementation might be there. But generally it sounds like we need a separate flag for transaction error handling that isn't tied to our regular error handling.

And yes: let's plan to do away with DBDebug altogether. Firing a `DatabaseErrorEvent` or something should be plenty for developers, along with the new exception handling feature.

2022-11-25 08:42 UTC, kenjis commented
I created an issue #6909

This PR is only for documentation update and adding test code.
Can I merge this? @codeigniter4/database-team

2022-11-25 17:48 UTC, michalsn requested changes
Shouldn't we also update the user guide if the general behavior in 4.3 has changed? If we're about to throw an exception every time, the examples in the user guide seem useless now.

I would like to see Transactions to be mentioned in the changelog. This is a critical change for someone who uses them.

2022-11-25 21:09 UTC, kenjis commented
Rebased.

2022-11-25 21:27 UTC, kenjis commented
Added about transactions in the changelog.

2022-11-26 16:05 UTC, michalsn reviewed
I think we still need some code examples in the user guide to show how to handle things when exceptions are thrown, since this will now be the default behavior.

2022-11-27 01:33 UTC, kenjis commented
I add a sample code and updated some descriptions.

I also found that SQLite3, Postgres and OCI8 drivers throw ErrorException when a query error occurs
because of Error Handler. See #6912
https://github.com/codeigniter4/CodeIgniter4/blob/ac1422c404a364f9493bbf1b22dacb18e3913982/system/Debug/Exceptions.php#L174-L176
So depending on the value of the error reporting setting, an exception may not be thrown.

2022-11-27 11:44 UTC, kenjis commented on user_guide_src/source/database/transactions/008.php
> +}
I still feel uncomfortable with this code.

2022-11-27 13:42 UTC, kenjis commented
> Perhaps a better way to handle this would be to have a parameter on `transStart()` or a separate method `transError(true/false)`.

See #6917

2022-11-27 14:34 UTC, michalsn commented
Well, I wasn't saying anything since everyone seemed to be on board regarding throwing exceptions, but... personally, I don't think that throwing exceptions for anything related to transactions has sense. This is why we have `transStatus()` - to handle errors.

So, for me #6917 is definitely a good way to solve this.

2022-11-28 01:11 UTC, kenjis commented
> So, for me https://github.com/codeigniter4/CodeIgniter4/pull/6917 is definitely a good way to solve this.

Yes, I also think it is necessary missing feature for v4.3.

2022-12-11 11:24 UTC, merged

2024-04-12 02:38 UTC, kenjis commented
@sclubricants I sent #8767