fix: socket connection in RedisHandler class
codeigniter4/CodeIgniter4 pull request #6972
Opened 2022-12-12 06:29 UTC by michalsn

**Description**
Fixes #6929

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

2022-12-13 01:06 UTC, ddevsr requested changes
Remove this changes

2022-12-13 01:06 UTC, ddevsr commented on user_guide_src/source/changelogs/v4.2.11.rst
> +- Fixed a ``FeatureTestTrait`` to use Services class for grabbing the ``IncomingRequest`` class.
```suggestion
```

2022-12-13 05:54 UTC, kenjis requested changes
Please fix the user guide. Except it this PR looks good.

2022-12-13 06:00 UTC, kenjis approved these changes
LGTM!

2022-12-13 06:26 UTC, merged

2024-02-23 01:47 UTC, kenjis commented
This fix seems to expect `$sessionSavePath` to be `/tmp/redis.sock`,
but should it be `unix:///var/run/redis/redis.sock?persistent=1&weight=1&database=0`?

See https://github.com/phpredis/phpredis?tab=readme-ov-file#php-session-handler
> phpredis can also connect to a unix domain socket: session.save_path = "unix:///var/run/redis/redis.sock?persistent=1&weight=1&database=0".

2024-02-23 01:57 UTC, kenjis commented
And this fix was broken by #7187.
https://github.com/codeigniter4/CodeIgniter4/pull/7187/files#diff-1a7b1fe40ddc58f0b240a268889a1952778b0631ce9db5f54cddaa359429dd60R140