feat: `spark route` option to sort by handler
codeigniter4/CodeIgniter4 pull request #7015
Opened 2022-12-24 02:08 UTC by kenjis

**Description**
Supersedes #6415

- add option `-h` to sort by handler

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

2022-12-24 10:26 UTC, datamweb commented on system/Commands/Utilities/Routes.php
>       * @var array
```suggestion
     * @var array<string, string>
```

2022-12-24 10:30 UTC, datamweb requested changes
Tested, good job!

![Screenshot 2022-12-24 135444](https://user-images.githubusercontent.com/9530214/209431920-9209a1b2-3340-4a80-a70f-02ea72b3d85f.jpg)

2022-12-26 03:53 UTC, ddevsr commented
Why not `-s` or `--sort`? In `-s` can be sort by handler or route or anything can be sort?

Like `-s handler` or `-s route`

2022-12-26 05:17 UTC, kenjis commented
`-h` for Handler.
The other options seem to be mostly unnecessary, so I went with `h`.

2022-12-26 08:04 UTC, michalsn approved these changes
`-h` make sense since I don't think there will be other functionality than sorting here.
But let's see if there will be more voices for the alternative solution.

2023-01-07 08:37 UTC, kenjis commented
@codeigniter4/core-team If everyone is okay, I would like to merge this.

2023-01-07 08:56 UTC, samsonasik approved these changes

2023-01-07 12:11 UTC, MGatner approved these changes
The sort arrow is a nice touch! 🤗

2023-01-07 23:33 UTC, merged