docs: add about Factories in upgrade_4xx
codeigniter4/CodeIgniter4 pull request #7203
Opened 2023-01-31 00:40 UTC by kenjis

**Description**
- add about Factories

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [] Conforms to style guide

2023-01-31 06:41 UTC, michalsn requested changes

2023-01-31 06:41 UTC, michalsn commented on user_guide_src/source/installation/upgrade_4xx.rst
> +- Ci4 provides :doc:`../concepts/factories` that can load a class and share the
```suggestion
- CI4 provides :doc:`../concepts/factories` that can load a class and share the
```

2023-02-01 15:23 UTC, datamweb approved these changes
I remember the documents in this section were not good, thank you!

2023-02-02 06:59 UTC, michalsn approved these changes

2023-02-02 07:10 UTC, merged