feat: add `Entity::injectRawData()` to avoid name collision
codeigniter4/CodeIgniter4 pull request #7208
Opened 2023-02-01 05:53 UTC by kenjis

**Description**
Supersedes #5763
Fixes #5762

- add `Entity::injectRawData()`
- deprecate `Entity::setAttributes()`
- require setter/getter methods must be public

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2023-02-01 08:00 UTC, iRedds commented
To be honest, I do not agree with this PR.
I believe that the implementation should be elegant like in laravel.
And adding reflection is already too much.
In my opinion, setters and getters should not be public, as they are specially made for the hidden implementation of logic.

2023-02-01 08:19 UTC, kenjis commented
Thank you for your comment.

> I believe that the implementation should be elegant like in laravel.

Can you elaborate? *elegant like in laravel* explains nothing to me.

2023-02-01 12:45 UTC, iRedds commented
To serve an entity
setAttributes()
getAttributes() instead of toRawArray()

setter and getter for attributes
set<AttributeName>Attribute()
get<AttributeName>Attribute()

Otherwise, any new entity functionality (method names) will need to be adjusted for the fact that the developer may have an attribute with the same name.

2023-02-06 11:17 UTC, MGatner requested changes
I don't see the public requirement being necessary here, and it is a very likely breaking change. We can discuss it here, or my preference would be to split it out into a separate PR and proceed with the injection method.

2023-02-07 08:41 UTC, kenjis commented
> I don't see the public requirement being necessary here, and it is a very likely breaking change. 

Indeed.

I dropped it.

2023-02-07 09:53 UTC, kenjis commented
@iRedds 
I don't think we need `getAttributes()`. The `attributes` property (or the word attributes) should not be actively disclosed. It is just an internal implementation.

2023-02-07 10:27 UTC, iRedds commented
@kenjis The ``getAttributes()`` method is the normal name for a class property getter. Just like ``setAttributes()``.

Sorry, but I don't agree with you.
The developer can create his own implementation of the model that works with the entity, which means that he must be able to receive data from the entity as is.
It is not clear to me what kind of **internal implementation** we are talking about.

2023-02-07 10:44 UTC, kenjis commented
In my opinion, the `attributes` property is not a normal property.
It should be hidden from users.

In fact, the attributes holds all the data for the record, but that is just the current implementation. 
There could be another implementation, and it does not matter if the name attributes is changed. 
It is an internal implementation and should be hidden.
Users do not need to be aware of it, and if they cannot use it without being aware of it, 
then it is poorly implemented.

2023-02-10 11:39 UTC, MGatner approved these changes
Looks good! Re: getAttributes()... how is this different than toRawArray()?

2023-02-11 01:54 UTC, kenjis commented
Added changelog.

2023-02-11 02:00 UTC, kenjis commented
I think this PR is ready to merge.

@mostafakhudair @najdanovicivan Any comments?

2023-02-12 08:51 UTC, najdanovicivan approved these changes

2023-02-13 23:43 UTC, merged

2023-02-13 23:43 UTC, kenjis commented
Thank you for the review! @MGatner @najdanovicivan