fix: FeatureTestTrait changes $params values passed to call()
codeigniter4/CodeIgniter4 pull request #7602
Opened 2023-06-21 01:20 UTC by kenjis

**Description**
Fixes #7593

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2023-06-21 05:14 UTC, iRedds commented
I would like to point out the incorrect handling of request parameters.
`FeatureTestTrait::populateGlobals()` method.
https://github.com/codeigniter4/CodeIgniter4/blob/52a2372addeb071f7deeb8418051554e2fba4149/system/Test/FeatureTestTrait.php#L341-L343

There are only two superglobal arrays that contain request data - _GET and _POST. 
That is, for example, for `$this->call('put', [...])`, this code should not be executed.

https://github.com/codeigniter4/CodeIgniter4/blob/52a2372addeb071f7deeb8418051554e2fba4149/system/Test/FeatureTestTrait.php#L345
The _REQUEST array will be populated if the request contains a query string and/or if the POST request was submitted with the content type `application/x-www-form-urlencoded` or `multipart/form-data`.
$_REQUEST = $_POST + $_GET;
In all other cases, _REQUEST must be empty.

I think it should look something like this.
```php
// regex is just for example.
if (
    $method == 'post'
    && ! empty($params)
    || ($this->bodyFormat === '' && preg_match('#^(.+=.+&?)+$#', $this->requestBody)) // a=b&c=d
) {
    if (empty($params) && preg_match('#^(.+=.+&?)+$#', $this->requestBody)) {
        parse_str($this->requestBody, $params);
    }

    $request->setGlobal('post', $params);
}

$request->setGlobal('request', $request->fetchGlobal('post') + $get);
```

`FeatureTestTrait::setRequestBody()` method.
https://github.com/codeigniter4/CodeIgniter4/blob/52a2372addeb071f7deeb8418051554e2fba4149/system/Test/FeatureTestTrait.php#L369-L371
This code doesn't make sense. Since _REQUEST will (should) be empty due to the above incorrect behavior.
And if the `$params` variable is empty, we can simply return the Request object.

2023-06-21 11:09 UTC, kenjis commented
@iRedds Fixed the code except parsing the body and setting the POST global.

The behavior of parsing the body and setting the POST global in the case of POST request is legitimate. 
However, I don't think it is necessary to bother writing such test code.
Because we can use the `$params` of `call()`.

2023-06-21 13:19 UTC, iRedds commented
@kenjis thanks for your work.

2023-06-29 23:22 UTC, kenjis commented
Can someone please review this?

2023-07-03 10:42 UTC, MGatner requested changes
One typo but otherwise looks great!

2023-07-03 10:42 UTC, MGatner commented on tests/system/Test/FeatureTestTraitTest.php
> +    public function testCallGetWithParamsAndREQEST()
```suggestion
    public function testCallGetWithParamsAndREQUEST()
```

2023-07-03 23:47 UTC, kenjis commented on tests/system/Test/FeatureTestTraitTest.php
> +    public function testCallGetWithParamsAndREQEST()
Thanks. Done.

2023-07-04 11:06 UTC, MGatner approved these changes

2023-07-04 22:54 UTC, merged