Dev: Remove the system-Exception ignore errors.
codeigniter4/CodeIgniter4 pull request #7791
Opened 2023-08-07 16:42 UTC by kai890707

**Description** 
See #7731
 
 **Checklist:**
 
 * [x]  Securely signed commits
 * [ ]  Component(s) with PHPDoc blocks, only if necessary or adds value
 * [ ]  Unit testing, with >80% coverage
 * [ ]  User guide updated
 * [x]  Conforms to style guide

2023-08-08 11:00 UTC, MGatner requested changes

2023-08-08 12:09 UTC, kai890707 commented on system/Exceptions/CastException.php
> +     * @return CastException
Thank you, I have edited it.

2023-08-09 07:27 UTC, paulbalandan commented on system/Exceptions/TestException.php
> +     * @return TestException
```suggestion
     * @return static
```

2023-08-09 10:13 UTC, datamweb approved these changes

2023-08-09 10:21 UTC, paulbalandan approved these changes

2023-08-10 05:06 UTC, kenjis commented
Please rebase to resolve conflicts.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch

2023-08-10 06:36 UTC, kai890707 commented
> Please rebase to resolve conflicts. See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch

I synchronized the current develop branch and ran phpstan.

2023-08-10 08:47 UTC, kenjis commented
> I synchronized the current develop branch and ran phpstan.

What is *synchronized* ? What did you do exactly? 

This branch is broken. See the diffs:
https://github.com/codeigniter4/CodeIgniter4/pull/7791/files

2023-08-11 01:07 UTC, kenjis commented
If you don't know how to use git, I recommend you try https://learngitbranching.js.org/

2023-08-16 15:54 UTC, closed without merging