Fix: Remove the  `Format`, `Log` and `Controller` ignore errors.
codeigniter4/CodeIgniter4 pull request #7795
Opened 2023-08-08 06:32 UTC by kai890707

**Description** 
See #7731
 
 **Checklist:**
 
 * [x]  Securely signed commits
 * [ ]  Component(s) with PHPDoc blocks, only if necessary or adds value
 * [ ]  Unit testing, with >80% coverage
 * [ ]  User guide updated
 * [x]  Conforms to style guide

2023-08-08 11:06 UTC, MGatner requested changes

2023-08-08 11:06 UTC, MGatner commented on system/Log/Exceptions/LogException.php
> +     * @return LogException
`static` here and below.

2023-08-08 12:25 UTC, kai890707 commented on system/Log/Exceptions/LogException.php
> +     * @return LogException
done.

2023-08-09 07:25 UTC, paulbalandan approved these changes

2023-08-10 03:59 UTC, kenjis approved these changes
LGTM!

2023-08-10 04:00 UTC, merged

2023-08-12 11:38 UTC, MGatner commented
🥳