Fix: Remove the ignore errors of `HTTP` in phpstan.
codeigniter4/CodeIgniter4 pull request #7803
Opened 2023-08-09 14:54 UTC by ya861220

**Description**
See #7731 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2023-08-10 04:39 UTC, datamweb requested changes

2023-08-10 04:39 UTC, datamweb commented on system/HTTP/DownloadResponse.php
>      private function setContentTypeByMimeType()
```suggestion
     */
    private function setContentTypeByMimeType(): void
```
see https://github.com/codeigniter4/CodeIgniter4/pull/7794#discussion_r1286958733

2023-08-10 05:02 UTC, ya861220 commented on system/HTTP/DownloadResponse.php
>      private function setContentTypeByMimeType()
Ok! Done.

2023-08-10 05:12 UTC, kenjis commented
Please rebase to resolve conflicts.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch

2023-08-12 01:38 UTC, kenjis commented on system/HTTP/Files/UploadedFileInterface.php
> +     * @return void
```suggestion
     * @return bool
```

2023-08-12 09:38 UTC, ya861220 commented on system/HTTP/Files/UploadedFileInterface.php
> +     * @return void
Ok! Done.

2023-08-12 09:46 UTC, kenjis approved these changes

2023-08-12 11:41 UTC, MGatner approved these changes

2023-08-12 11:41 UTC, MGatner commented
Thank you!

2023-08-12 11:41 UTC, merged