docs: improve description for Factories BC
codeigniter4/CodeIgniter4 pull request #7840
Opened 2023-08-18 21:51 UTC by kenjis

**Description**
See https://forum.codeigniter.com/showthread.php?tid=87335&pid=411906#pid411906

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [] Conforms to style guide

2023-08-20 11:56 UTC, MGatner requested changes
I like the change to "with namespace". Some readability suggestions.

2023-08-20 11:56 UTC, MGatner commented on user_guide_src/source/changelogs/v4.4.0.rst
> +For example, in a controller (``namespace App\Controllers``), if you call
```suggestion
For example, in a controller (``namespace App\Controllers``), if you called
```

2023-08-20 11:56 UTC, MGatner commented on user_guide_src/source/changelogs/v4.4.0.rst
> +``config(Config\App::class)`` by mistake (note that you forgot the leading ``\``
```suggestion
``config(Config\App::class)`` by mistake (note the class is missing the leading ``\``),
```

2023-08-20 11:56 UTC, MGatner commented on user_guide_src/source/changelogs/v4.4.0.rst
> +in ``Config\App::class``), that means you pass ``App\Controllers\Config\App``.
```suggestion
meaning you actually passed ``App\Controllers\Config\App``.
```

2023-08-20 11:56 UTC, MGatner commented on user_guide_src/source/changelogs/v4.4.0.rst
> +But the class does not exist, so now Factories return ``null``.
```suggestion
But that class does not exist, so now Factories will return ``null``.
```

2023-08-21 01:03 UTC, kenjis commented
Updated!
![Screenshot from 2023-08-21 10-02-37](https://github.com/codeigniter4/CodeIgniter4/assets/87955/d3c1bbd9-2a16-46bc-aee4-506dfecc92d0)

2023-08-23 11:02 UTC, MGatner approved these changes

2023-08-23 11:36 UTC, merged