GH: auto labeling unsigned PR
codeigniter4/CodeIgniter4 pull request #7938
Opened 2023-09-13 09:16 UTC by ddevsr

**Description**
I think this help

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2023-09-13 12:33 UTC, MGatner requested changes
Checkout v4 is going to take some getting used to 😉

This looks like a great addition.

2023-09-13 12:33 UTC, MGatner commented on .github/workflows/label-signing.yml
> +        uses: actions/checkout@v3
```suggestion
        uses: actions/checkout@v4
```

2023-09-13 12:47 UTC, MGatner approved these changes
LGTM!

2023-09-14 01:27 UTC, kenjis commented on .github/workflows/label-signing.yml
> +  issues: write
Why do you need `issues: write`?

2023-09-14 03:12 UTC, ddevsr commented on .github/workflows/label-signing.yml
> +  issues: write
No need, already remove

2023-09-14 04:31 UTC, kenjis approved these changes

2023-09-14 04:32 UTC, merged

2023-12-12 21:13 UTC, kenjis commented
```
Run 1Password/check-signed-commits-action@v1
Run unsigned_commits="$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$COMMITS_URL" | jq '.[] | select(.commit.verification.verified == false) | .commit.message')"
Found unsigned commits:
"Skip hostname checks if CURLRequest options 'verify' is set to false.\n\nWhen CURLRequest options 'verify' is set to false, some CURLOPT_SSL_... options should be disabled in such a way as to allow requests to pass through in case the destination is for example on private networks."
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   743  100   153  100   590    444   1714 --:--:-- --:--:-- --:--:--  2159
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/issues/comments#create-an-issue-comment"
}
Error: Process completed with exit code 1.
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/6993466495/job/19026745521

2023-12-12 21:46 UTC, kenjis commented
To post comments, it seems `pull_request_target` is needed:
https://github.com/1Password/check-signed-commits-action#pull_request_target-vs-pull_request