docs: [CLI] make public properties deprecated
codeigniter4/CodeIgniter4 pull request #7976
Opened 2023-09-25 22:03 UTC by kenjis

**Description**
No need to be public.

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

2023-09-28 07:03 UTC, mostafakhudair requested changes

2023-09-28 11:05 UTC, kenjis commented on system/CLI/CLI.php
The property name is not good, but I don't have a plan to change it.
The future is uncertain.

2023-10-10 11:13 UTC, MGatner approved these changes
I like @mostafakhudair 's suggestions but since this class isn't `final` they introduce another layer of breaking changes. Consider for next major version.

2023-10-10 21:11 UTC, kenjis commented
@mostafakhudair @MGatner I added `@TODO` as reminder.

2023-10-11 04:11 UTC, merged