docs: improve View pages
codeigniter4/CodeIgniter4 pull request #8780
Opened 2024-04-14 00:43 UTC by kenjis

**Description**
- minor improvements

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [] Conforms to style guide

2024-04-14 00:50 UTC, datamweb requested changes

2024-04-14 00:50 UTC, datamweb commented on user_guide_src/source/outgoing/view_parser.rst
> +``blog_template``` is the name of your view template file.
```suggestion
``blog_template`` is the name of your view template file.
```

2024-04-14 15:06 UTC, ddevsr approved these changes

2024-04-15 12:55 UTC, paulbalandan approved these changes

2024-04-16 00:04 UTC, merged