docs: @param BaseBuilder.php
codeigniter4/CodeIgniter4 pull request #8808
Opened 2024-04-19 10:03 UTC by ddevsr

**Description**
See https://github.com/codeigniter4/CodeIgniter4/actions/runs/8748888596/job/24009622239

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

2024-04-19 10:11 UTC, samsonasik requested changes
phpstan baseline need to be regenerated

2024-04-19 22:11 UTC, kenjis commented on system/Database/BaseBuilder.php
> +     * @param list<int|string> $unescapedKeys QBSet
`Keys of QBSet` and `Values of QBSet`?

2024-04-23 01:10 UTC, kenjis commented on system/Database/BaseBuilder.php
> +     * @param list<int|string>|RawSql|string $field
This is incorrect. See https://codeigniter4.github.io/CodeIgniter4/database/query_builder.html#id5

Like this?
```suggestion
     * @param array<string, string>|RawSql|string $field
```

2024-04-23 09:00 UTC, kenjis approved these changes

2024-04-26 00:11 UTC, merged