docs: Fix typos and add missing preferences in libraries/email.rst
codeigniter4/CodeIgniter4 pull request #8851
Opened 2024-05-04 14:36 UTC by obozdag

**Description**
Fix typos and add missing preferences in libraries/email.rst

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [ ] Conforms to style guide

2024-05-05 08:35 UTC, kenjis commented on user_guide_src/source/libraries/email.rst
> +**$DSN**            false               ``true``/``false``           Enable notify message from server.
Please remove all `$` marks in `Preference`.
Because these items may be keys in an array.

2024-05-05 08:44 UTC, kenjis commented on user_guide_src/source/libraries/email.rst
> +**$recipients**                                                      The email addresses of the recipients, as a comma separated string or
Do we really need this `recipients` ?

2024-06-10 08:26 UTC, obozdag commented
@kenjis What kind of rework does it need? Should I remove $recipients or $ marks or both?

2024-06-10 08:32 UTC, kenjis commented
@obozdag Yes.

2024-06-10 08:37 UTC, kenjis commented on user_guide_src/source/libraries/email.rst
> +**$recipients**                                                      The email addresses of the recipients, as a comma separated string or
I think `recipients` is not needed. It is set when we send emails.

2024-07-24 00:36 UTC, kenjis commented on user_guide_src/source/libraries/email.rst
> +**$protocol**       mail                ``mail``, ``sendmail``,      The mail sending protocol.
Please remove all `$` marks in `Preference`.
Because these items may be keys in an array.

2024-07-24 00:36 UTC, kenjis commented on user_guide_src/source/libraries/email.rst
> +**$SMTPPort**       25                                               SMTP Port. (If set to ``465``, TLS will be used for the connection
Please remove all `$` marks in `Preference`.
Because these items may be keys in an array.

2024-07-24 00:36 UTC, kenjis commented on user_guide_src/source/libraries/email.rst
> +**$SMTPCrypto**     tls                 ``tls``, ``ssl``, or         SMTP Encryption. Setting this to ``ssl`` will create a secure
Please remove all `$` marks in `Preference`.
Because these items may be keys in an array.

2024-07-24 00:36 UTC, kenjis commented on user_guide_src/source/libraries/email.rst
> +**$mailType**       text                ``text`` or ``html``         Type of mail. If you send HTML email you must send it as a complete web
Please remove all `$` marks in `Preference`.
Because these items may be keys in an array.

2024-07-24 00:37 UTC, kenjis requested changes
Please remove all `$` marks in `Preference`.
Because these items may be keys in an array.

2024-07-24 03:24 UTC, obozdag commented
@kenjis I have removed all $ marks in Preference.
In https://codeigniter4.github.io/CodeIgniter4/libraries/cookies.html#cookie-personalization there are $ marks and they can be keys in the defaults array. So, shall I also remove the $ marks there?

2024-07-24 04:00 UTC, kenjis approved these changes

2024-07-24 04:13 UTC, kenjis commented
@obozdag Thank you!

> In https://codeigniter4.github.io/CodeIgniter4/libraries/cookies.html#cookie-personalization there are $ marks and they can be keys in the defaults array. So, shall I also remove the $ marks there?

I'm not sure. Because the description for the table is:

> However, you may wish to define your own settings by changing the following settings in the Config\Cookie class in app/Config/Cookie.php file.

So it clearly indicates that the table explains properties in `Config\Cookie`.
But yes, the items are also array keys for `Cookie::setDefaults()`.

2024-07-24 04:48 UTC, paulbalandan commented
I think I mean here when I made the table is it is referring to the properties of `Config\Cookie` so the `$` should be preserved. The array keys to `Cookie::$defaults` are private implementation details.

2024-07-24 04:51 UTC, paulbalandan approved these changes

2024-07-25 01:05 UTC, merged

2024-07-25 01:05 UTC, kenjis commented
@obozdag Thank you!