docs: Fix some typos in helpers/html_helper.rst
codeigniter4/CodeIgniter4 pull request #8916
Opened 2024-05-26 19:46 UTC by obozdag

**Description**
Fix some typos in helpers/html_helper.rst

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [ ] Conforms to style guide

2024-05-27 01:43 UTC, kenjis commented on user_guide_src/source/helpers/html_helper.rst
> +    .. literalinclude:: html_helper/019.php
These differences make it difficult to review.
I don't know why `track()` location was changed.
Please create one commit for changing the position.

Also, there are too many diffs in one commit. 
Many fixes are corrections of errors, and it is too large to be called typos.
Please create a commit with a commit log of what you changed for every single meaningful fix.

2024-05-28 01:38 UTC, ddevsr commented on user_guide_src/source/helpers/html_helper.rst
> +    Presumably, this would be true if you were using a media controller???:
```suggestion
    Presumably, this would be true if you were using a media controller:
```

2024-06-10 12:27 UTC, paulbalandan approved these changes

2024-08-12 00:40 UTC, kenjis requested changes
Could you please re-create this PR so that each meaningful change is committed as one git commit? Because I cannot review this PR.

E.g., 
a commit to move a paragraph. 
a commit to replace tags with elements.
a commit to fix one function description.

2024-09-06 00:12 UTC, kenjis commented
Closed by #9153, #9161, #9162, #9163, #9164

2024-09-06 00:12 UTC, closed without merging