Update protected function setBind  for permitting complex key binds
codeigniter4/CodeIgniter4 pull request #9049
Opened 2024-07-17 09:36 UTC by berengan

Anonymize bind key for complex query  like CONCAT(field1, ' ', field2 ) LIKE '%value%'

the bind :CONCAT(field1, ' ', field2 )  does not work

**Description**
on a query sample : CONCAT(field1, ' ', field2 ) LIKE '%value%'
the bind :CONCAT(field1, ' ', field2 )  does not work 
the key on setBind is now an md5 of original.

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

2024-07-17 11:52 UTC, berengan commented
To reply the error use :
CONCAT(IF(field1 = 'x' OR field1 = 'y', field2,  field3)) LIKE '%value%'

on several test the OR sintax crashed the bind

2024-07-17 20:47 UTC, kenjis commented
Thank you for sending this PR!

We expect the following in all Pull Requests (PRs).
- PRs must be sent to the [appropriate branch](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#branching)
- All git commits must be [GPG-signed](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing)
- Must follow our [style guide](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style)
- Be [commented](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#comments) in the PHP source file
- Be documented in the [user guide](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#user-guide)
- Be [unit tested](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing)
- Pass all checks in GitHub Actions

> [!IMPORTANT]
> We expect all code changes or bug-fixes to be accompanied by one or more tests added to our test suite to prove the code works.

If pull requests do not comply with the above, they will likely be closed. Since we are a team of volunteers, we don't have any more time to work on the framework than you do. Please make it as painless for your contributions to be included as possible.

See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

2024-07-17 23:54 UTC, kenjis commented
What's the exact issue that you want to solve?

I don't think the following SQL statements are good.
I disagree with these changes.

```diff
1) CodeIgniter\Database\Builder\CountTest::testCountAllResults
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'SELECT COUNT(*) AS "numrows" FROM "jobs" WHERE "id" > :id:'
+'SELECT COUNT(*) AS "numrows" FROM "jobs" WHERE "id" > :b80bb7740288fda1f201890375a60c8f:'

/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/Builder/CountTest.php:55

2) CodeIgniter\Database\Builder\CountTest::testCountAllResultsWithGroupBy
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'SELECT COUNT(*) AS "numrows" FROM ( SELECT * FROM "jobs" WHERE "id" > :id: GROUP BY "id" ) CI_count_all_results'
+'SELECT COUNT(*) AS "numrows" FROM ( SELECT * FROM "jobs" WHERE "id" > :b80bb7740288fda1f201890375a60c8f: GROUP BY "id" ) CI_count_all_results'

/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/Builder/CountTest.php:68

3) CodeIgniter\Database\Builder\CountTest::testCountAllResultsWithGroupByAndPrefix
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'SELECT COUNT(*) AS "numrows" FROM ( SELECT "ci_jobs".* FROM "ci_jobs" WHERE "id" > :id: GROUP BY "id" ) CI_count_all_results'
+'SELECT COUNT(*) AS "numrows" FROM ( SELECT "ci_jobs".* FROM "ci_jobs" WHERE "id" > :b80bb7740288fda1f201890375a60c8f: GROUP BY "id" ) CI_count_all_results'

/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/Builder/CountTest.php:84
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/9971838920/job/27586979257?pr=9049

2024-07-17 23:57 UTC, kenjis requested changes
I disagree with this change.

2024-07-18 16:32 UTC, michalsn reviewed
I don't understand what this change is supposed to bring.

2024-08-21 09:09 UTC, kenjis commented
> [!IMPORTANT]
> We expect all code changes or bug-fixes to be accompanied by one or more tests
> added to our test suite to prove the code works.

This PR does not have the necessary test code. If you want this PR to be reviewed, please add the test code.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#unit-testing

If the test is not added, this PR will be closed.

2024-08-26 04:07 UTC, closed without merging