Fix: Parser - Equal key name replace conflict
codeigniter4/CodeIgniter4 pull request #9246
Opened 2024-10-30 16:35 UTC by CosDiabos

**Description**
Fixes the conflict when replacing View Parser {variables} in the provided data with the same key name, even when on different levels.

This fix focus on ```parse()``` method, in which the return of ```parsePair``` and ```parseSingle``` methods are stored independently , then merged together (Pairs with Single), and finally replaced. With this approach, the replacement happens from the Pairs to Single and the output is as expected.

More details and examples in issue #9245 

Fixes #9245 

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

2024-10-30 16:48 UTC, samsonasik commented
Run Rector and cs fix:

```
vendor/bin/rector && composer cs-fix
```

also, a test case seems needed.

2024-10-31 20:55 UTC, samsonasik commented
You can rename PR title with `fix: ` prefix

2024-11-01 06:56 UTC, mostafakhudair commented on system/View/Parser.php
> +                $replacePairsStack[] = ['replace' => $this->parsePair($key, $val, $template), 'escape' => $escape];
```suggestion
                $escape              = false;
                $replacePairsStack[] = [
                    'replace' => $this->parsePair($key, $val, $template),
                    'escape'  => $escape,
                ];
```

2024-11-01 06:57 UTC, mostafakhudair commented on system/View/Parser.php
>              }
```suggestion
                $replaceSingleStack[] = [
                    'replace' => $this->parseSingle($key, (string) $val),
                    'escape'  => $escape,
                ];
            }
```

2024-11-01 16:33 UTC, datamweb commented
@CosDiabos To ensure the security and authenticity of your commits, please sign **all** of them with GPG. This shows others that the commits were genuinely made by you and can be trusted.

For a detailed guide on signing commits with GPG, please refer to [gpg-signing-old-commits](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#gpg-signing-old-commits).

2024-11-01 17:27 UTC, CosDiabos commented
Thank you all for your help!

2024-11-02 15:46 UTC, michalsn requested changes
@CosDiabos Looks great! We need one last thing - a changelog entry.

Please add it under the Bugs Fixed section, here: https://github.com/codeigniter4/CodeIgniter4/blob/develop/user_guide_src/source/changelogs/v4.5.6.rst

Something like: 
> **Parser**: Fixed a bug that caused equal key names to be replaced by the key defined first.

Thanks.

2024-11-02 18:22 UTC, michalsn approved these changes

2024-11-03 17:44 UTC, merged

2024-11-03 17:45 UTC, michalsn commented
@CosDiabos Thank you for your first contribution!