fix: [CURLRequest] body contains "HTTP/1.0 200 Connection established"
codeigniter4/CodeIgniter4 pull request #9285
Opened 2024-11-18 08:57 UTC by ping-yee

**Description**
Fix #8526

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

2024-11-18 16:36 UTC, michalsn requested changes
Looks good! Please add a changelog entry.

2024-11-28 12:59 UTC, ping-yee commented
@michalsn Done. review please.

2024-11-29 08:11 UTC, michalsn approved these changes
Thank you.

2024-11-29 17:01 UTC, paulbalandan approved these changes

2024-11-29 17:01 UTC, merged