feat: Strict locale negotiate
codeigniter4/CodeIgniter4 pull request #9360
Opened 2024-12-31 16:42 UTC by neznaika0

**Description**
See #9256
I added a setting for the desired behavior.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

2025-01-01 08:27 UTC, michalsn reviewed
While this may be a solution for some simpler cases, I think more complex ones won't be so simple.

If we take `$supportedLocales` as an array of `en_US`, `fr_FR`, and the browser is set to `fr_BE`, the loaded locale will be `en_US`. Is this the desired result? We can argue about that.

I think in this case changes would be needed to select the fallback locale.

I'm curious what others think about it.

2025-01-01 08:27 UTC, michalsn commented on app/Config/Feature.php
> +    public bool $simpleNegotiateLocale = true;
```suggestion
    public bool $strictLocaleNegotiation = false;
```

It seems more accurate.

2025-01-01 08:27 UTC, michalsn commented on app/Config/Feature.php
> +     */
We should indicate that changing this will also require modifying the language files' folder names.

This should be also documented in the user guide - not only in the changelog.

2025-01-01 08:43 UTC, neznaika0 commented on app/Config/Feature.php
> +    public bool $simpleNegotiateLocale = true;
I would not like to invert the value `$a ? false : true`

2025-01-01 08:51 UTC, neznaika0 commented
> If we take $supportedLocales as an array of en_US, fr_FR, and the browser is set to fr_BE, the loaded locale will be en_US. Is this the desired result? We can argue about that.

It current behavior - select first element array

2025-01-01 08:52 UTC, neznaika0 commented on app/Config/Feature.php
> +     */
Ok. Later. Later. But I need help with the translation

2025-01-01 08:55 UTC, michalsn commented
Yes, I know. While it makes sense when we compare locales loosely. I don't believe it should work that way with strict comparison. Fallback should search for the best match.

2025-01-01 09:04 UTC, neznaika0 commented
What would be better than the first (main) element of the array?

2025-01-01 11:00 UTC, michalsn commented
> What would be better than the first (main) element of the array?

In the example I presented it would be `fr_FR`.

We would have to search for the best matching option. It would be `fr` as a first choice (if available is `$supportedLocales`) or `fr_FR`.

2025-01-01 11:02 UTC, michalsn commented on app/Config/Feature.php
> +    public bool $simpleNegotiateLocale = true;
How about `$looseLocaleNegotiation` then?

2025-01-02 10:42 UTC, neznaika0 commented
I tried to add logic to find the nearest locale. But it looks bad.

I added a repeat search for `fr` if the locale from the request (result best-match) does not start with `fr` and returned the first `fr-BE` instead of `en-US`. 

Can I save the first variant?

2025-01-02 11:14 UTC, michalsn commented
How about something like this? Although I haven't tested it yet...
```php
protected function getBestLocaleMatch(array $supported, ?string $header): string
{
    if ($supported === []) {
        throw HTTPException::forEmptySupportedNegotiations();
    }

    if ($header === null || $header === '') {
        return $supported[0];
    }

    $acceptable      = $this->parseHeader($header);
    $fallbackLocales = [];

    foreach ($acceptable as $accept) {
        // if acceptable quality is zero, skip it.
        if ($accept['q'] === 0.0) {
            continue;
        }

        // if acceptable value is "anything", return the first available
        if ($accept['value'] === '*') {
            return $supported[0];
        }

        // look for exact match
        if (in_array($accept['value'], $supported, true)) {
            return $accept['value'];
        }

        // set a fallback locale
        $fallbackLocales[] = strtok($accept['value'], '-');
    }

    foreach ($fallbackLocales as $fallbackLocale) {
        // look for exact match
        if (in_array($fallbackLocale, $supported, true)) {
            return $fallbackLocale;
        }

        // look for locale variants match
        foreach ($supported as $locale) {
            if (str_starts_with($locale, $fallbackLocale . '-')) {
                return $locale;
            }
        }
    }

    return $supported[0];
}
```

For `$supportedLocales` set to `['en-US', 'fr-FR']`, it will first check for all the options from the `Accept-Language` header. If no exact match is found, it will check the "general locale": `en` and then the "locale variant": `en-*`. The `en` is just an example, the values will come from the parsed header.

2025-01-02 11:43 UTC, neznaika0 commented
I did something similar, but right in the `language()` method. It seems to me that duplication is not good.

2025-01-02 11:59 UTC, michalsn commented
Oh... I would definitely choose a separate method. Even if some small parts are the same, the main goal is to make it as readable as possible.

2025-01-03 12:15 UTC, neznaika0 commented
Ready. 

I would pay attention to the description. It is not completely correct. Depends on the array of locales and the query. Sometimes it works, sometimes it returns `en` instead of `en-US`. Is the reason for PR. Is there any way to describe it?
https://github.com/codeigniter4/CodeIgniter4/blob/046967af08b9c0138aeaec45a6570406a229ae08/user_guide_src/source/outgoing/localization.rst?plain=1#L34-L37

2025-01-03 12:50 UTC, paulbalandan commented on app/Config/Feature.php
> +     * Set `false` to use strict localization comparison (with territory en-*) instead of an abbreviated value.
```suggestion
     * Set `false` to use strict localization comparison (e.g., against locale code `en-US` instead of the ISO 639-1 language code `en`)
```

2025-01-03 12:50 UTC, paulbalandan commented on app/Config/Feature.php
> +     * Set `true`, so territory was cut off (en-* as en) before localization comparing.
```suggestion
     * If set to `true`, the ISO 3166-1 region code will be cut off (e.g., `en-US` as `en`) before localization comparison.
```

2025-01-03 12:50 UTC, paulbalandan commented on system/HTTP/Negotiate.php
> +    protected function getBestLocaleMatch(array $supported, ?string $header): string
It may be better to use nouns here.
```suggestion
    protected function getBestLocaleMatch(array $supportedLocales, ?string $header): string
```

2025-01-03 12:50 UTC, paulbalandan commented on user_guide_src/source/installation/upgrade_458.rst
> +- @TODO
what changed here?

2025-01-03 12:50 UTC, paulbalandan commented on user_guide_src/source/installation/upgrade_460.rst
> +- app/Config/Feature.php
you can remove the todo below

2025-01-03 12:50 UTC, paulbalandan commented on user_guide_src/source/installation/upgrade_460.rst
> -
pls readd the new line

2025-01-03 14:02 UTC, michalsn commented on user_guide_src/source/changelogs/v4.6.0.rst
> +  Set the value to ``false`` to be able to get ``en-*``
```suggestion
  Set the value to ``true`` to enable comparison not only by language code ('en' - ISO 639-1) but also by regional code ('en-US' - ISO 639-1 plus ISO 3166-1 alpha).
```

2025-01-03 14:02 UTC, michalsn commented on user_guide_src/source/incoming/content_negotiation.rst
> +
```suggestion
Strict Locale Negotiation
-------------------------

.. versionadded:: 4.6.0

By default, locale is determined on a lossy comparison basis. So only the first part of the locale string is taken
into account (language). This is usually sufficient. But sometimes we want to be able to distinguish between regional versions such as
``en-US`` and ``en-GB`` to serve different content.

For such cases, we have introduced a new setting that can be enabled via ``Config\Feature::$strictLocaleNegotiation``. This will ensure
that the strict comparison will be made in the first place.

.. note::

    CodeIgniter comes with translations only for primary language tags ('en', 'fr', etc.). So if you enable this feature and your
    settings in ``Config\App::$supportedLocales`` include regional language tags ('en-US', 'fr-FR', etc.), then keep in mind that
    if you have your own translation files, you **must also change** the folder names for CodeIgniter's translation files to match
    what you put in the ``$supportedLocales`` array.

Now let's consider the below example. The browser's preferred language will be set as this::

    GET /foo HTTP/1.1
    Accept-Language: fr; q=1.0, en-GB; q=0.5

In this example, the browser would prefer French, with a second choice of English (United Kingdom). Your website on another hand will
supports German and English (United States):

.. code-block:: php

    $supported = [
        'de',
        'en-US',
    ];

    $lang = $request->negotiate('language', $supported);
    // or
    $lang = $negotiate->language($supported);

In this example, 'en-US' would be returned as the current language. If no match is found, it will return the first element
in the ``$supported`` array. Here is how exactly the locale selection process works.

Even though the 'fr' is preferred by the browser it is not in our ``$supported`` array. The same problem occurs with 'en-GB', but here
we will be able to search for variants. First, we will fallback to the most general locale (in this case 'en') which again is not in our
array. Then we will search for the regional locale 'en-'. And that's when our value from the ``$supported`` array will be matched.
We will return 'en-US'.

So the process of selecting a locale is as follows:

#. strict match ('en-GB') - ISO 639-1 plus ISO 3166-1 alpha-2
#. general locale match ('en') - ISO 639-1
#. regional locale match ('en-') - ISO 639-1 plus "wildcard" for ISO 3166-1 alpha-2
```

2025-01-03 14:02 UTC, michalsn commented on user_guide_src/source/installation/upgrade_460.rst
> +    - ``Config\Feature::$looseLocaleNegotiation`` has been added.
```suggestion
    - ``Config\Feature::$strictLocaleNegotiation`` has been added.
```

2025-01-03 14:54 UTC, neznaika0 commented
Pff.. See https://github.com/codeigniter4/CodeIgniter4/pull/9360#discussion_r1900346976 - we changed it to `looseLocaleNegotiation`. 

Again, my small changes overlap with your additions. 😄

2025-01-03 15:05 UTC, michalsn commented
> Pff.. Again, my small changes overlap with your additions. 😄

Yeah, I know - sorry, but I believe this will fit better. I hope I explained my reasons.

2025-01-03 15:33 UTC, neznaika0 commented on app/Config/Feature.php
> +     * Set `false` to use strict localization comparison (with territory en-*) instead of an abbreviated value.
I will accept michalsn's correction.

2025-01-03 15:33 UTC, neznaika0 commented on app/Config/Feature.php
> +     * Set `true`, so territory was cut off (en-* as en) before localization comparing.
I will accept michalsn's correction.

2025-01-03 15:50 UTC, neznaika0 commented on user_guide_src/source/installation/upgrade_458.rst
> +- @TODO
I restore code, maybe space?

2025-01-03 16:07 UTC, neznaika0 commented on system/HTTP/Negotiate.php
> +        if (config(Feature::class)->looseLocaleNegotiation) {
Your condition is wrong

```php
        if (config(Feature::class)->strictLocaleNegotiation) {
            return $this->getBestLocaleMatch($supported, $this->request->getHeaderLine('accept-language'));
        }

        return $this->getBestMatch($supported, $this->request->getHeaderLine('accept-language'), false, false, true);
```

2025-01-03 16:16 UTC, neznaika0 reviewed
Ready.

2025-01-04 08:20 UTC, crustamet commented
i am eagerly wating for this update to go trough :D

2025-01-04 08:32 UTC, michalsn commented
The changes are hanging. It looks like GitHub is fighting against this PR 😅 

@neznaika0 can you try to rebase?

2025-01-04 09:59 UTC, neznaika0 commented
Ok. I'm rebasing last commit again

2025-01-04 10:07 UTC, michalsn requested changes
Thanks, I spotted two things.

2025-01-04 10:07 UTC, michalsn commented on system/HTTP/Negotiate.php
> +            if ($accept['value'] === '*' || $accept['value'] === '*/*') {
There is no option for the `Accept-Language` header to have a `*/*` value.

2025-01-04 10:07 UTC, michalsn commented on user_guide_src/source/incoming/content_negotiation.rst
> +    $lang = $negotiate->language($supported);
Please use `.. literalinclude::` just like we do in the other code blocks. I had no choice but to use this syntax when I proposed the changes.

2025-01-04 10:16 UTC, neznaika0 commented on system/HTTP/Negotiate.php
> +            if ($accept['value'] === '*' || $accept['value'] === '*/*') {
Thanks. Really, `*/*` this is for `image/png` matches

2025-01-04 10:37 UTC, neznaika0 commented
Success. 
![Снимок экрана от 2025-01-04 13-33-26](https://github.com/user-attachments/assets/0dcd3e82-5233-43aa-a1fb-ec49357650a4)

2025-01-04 10:43 UTC, michalsn commented on user_guide_src/source/incoming/content_negotiation.rst
> +    Now let's consider the below example. The browser's preferred language will be set as this::
```suggestion
Now let's consider the below example. The browser's preferred language will be set as this::
```
This should not be part of the "Note". I found it based on your screenshot - thanks!

2025-01-04 13:36 UTC, paulbalandan commented on user_guide_src/source/incoming/content_negotiation.rst
> +In this example, the browser would prefer French, with a second choice of English (United Kingdom). Your website on another hand will
remove the will?
```suggestion
In this example, the browser would prefer French, with a second choice of English (United Kingdom). Your website on another hand
```

2025-01-04 14:00 UTC, michalsn commented on user_guide_src/source/incoming/content_negotiation.rst
> +In this example, the browser would prefer French, with a second choice of English (United Kingdom). Your website on another hand will
Not sure, but I will trust your judgment.

2025-01-04 18:08 UTC, paulbalandan approved these changes

2025-01-05 04:40 UTC, merged

2025-01-05 04:40 UTC, paulbalandan commented
Thank you, @neznaika0